/*
otari-gateway

A clean FastAPI gateway for otari with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the CCChatCompletionAudio type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CCChatCompletionAudio{}

// CCChatCompletionAudio If the audio output modality is requested, this object contains data about the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).
type CCChatCompletionAudio struct {
	Id                   string `json:"id"`
	Data                 string `json:"data"`
	ExpiresAt            int32  `json:"expires_at"`
	Transcript           string `json:"transcript"`
	AdditionalProperties map[string]interface{}
}

type _CCChatCompletionAudio CCChatCompletionAudio

// NewCCChatCompletionAudio instantiates a new CCChatCompletionAudio object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCCChatCompletionAudio(id string, data string, expiresAt int32, transcript string) *CCChatCompletionAudio {
	this := CCChatCompletionAudio{}
	this.Id = id
	this.Data = data
	this.ExpiresAt = expiresAt
	this.Transcript = transcript
	return &this
}

// NewCCChatCompletionAudioWithDefaults instantiates a new CCChatCompletionAudio object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCCChatCompletionAudioWithDefaults() *CCChatCompletionAudio {
	this := CCChatCompletionAudio{}
	return &this
}

// GetId returns the Id field value
func (o *CCChatCompletionAudio) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CCChatCompletionAudio) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CCChatCompletionAudio) SetId(v string) {
	o.Id = v
}

// GetData returns the Data field value
func (o *CCChatCompletionAudio) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CCChatCompletionAudio) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CCChatCompletionAudio) SetData(v string) {
	o.Data = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CCChatCompletionAudio) GetExpiresAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CCChatCompletionAudio) GetExpiresAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CCChatCompletionAudio) SetExpiresAt(v int32) {
	o.ExpiresAt = v
}

// GetTranscript returns the Transcript field value
func (o *CCChatCompletionAudio) GetTranscript() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Transcript
}

// GetTranscriptOk returns a tuple with the Transcript field value
// and a boolean to check if the value has been set.
func (o *CCChatCompletionAudio) GetTranscriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transcript, true
}

// SetTranscript sets field value
func (o *CCChatCompletionAudio) SetTranscript(v string) {
	o.Transcript = v
}

func (o CCChatCompletionAudio) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CCChatCompletionAudio) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["data"] = o.Data
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["transcript"] = o.Transcript

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CCChatCompletionAudio) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"data",
		"expires_at",
		"transcript",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCCChatCompletionAudio := _CCChatCompletionAudio{}

	err = json.Unmarshal(data, &varCCChatCompletionAudio)

	if err != nil {
		return err
	}

	*o = CCChatCompletionAudio(varCCChatCompletionAudio)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "data")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "transcript")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCCChatCompletionAudio struct {
	value *CCChatCompletionAudio
	isSet bool
}

func (v NullableCCChatCompletionAudio) Get() *CCChatCompletionAudio {
	return v.value
}

func (v *NullableCCChatCompletionAudio) Set(val *CCChatCompletionAudio) {
	v.value = val
	v.isSet = true
}

func (v NullableCCChatCompletionAudio) IsSet() bool {
	return v.isSet
}

func (v *NullableCCChatCompletionAudio) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCCChatCompletionAudio(val *CCChatCompletionAudio) *NullableCCChatCompletionAudio {
	return &NullableCCChatCompletionAudio{value: val, isSet: true}
}

func (v NullableCCChatCompletionAudio) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCCChatCompletionAudio) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
