/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ValidateInvitationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateInvitationRequest{}

// ValidateInvitationRequest The preview lookup's body.  A “POST“ with the token in the body rather than a “GET“ with it in the URL, matching “AcceptInvitationRequest“: the token is a bearer-style credential (see “Invitation.token_hash“'s docstring), and a URL is one a proxy or an access log routinely retains, which a request body is not.
type ValidateInvitationRequest struct {
	Token string `json:"token"`
}

type _ValidateInvitationRequest ValidateInvitationRequest

// NewValidateInvitationRequest instantiates a new ValidateInvitationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateInvitationRequest(token string) *ValidateInvitationRequest {
	this := ValidateInvitationRequest{}
	this.Token = token
	return &this
}

// NewValidateInvitationRequestWithDefaults instantiates a new ValidateInvitationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateInvitationRequestWithDefaults() *ValidateInvitationRequest {
	this := ValidateInvitationRequest{}
	return &this
}

// GetToken returns the Token field value
func (o *ValidateInvitationRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ValidateInvitationRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ValidateInvitationRequest) SetToken(v string) {
	o.Token = v
}

func (o ValidateInvitationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateInvitationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *ValidateInvitationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateInvitationRequest := _ValidateInvitationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateInvitationRequest)

	if err != nil {
		return err
	}

	*o = ValidateInvitationRequest(varValidateInvitationRequest)

	return err
}

type NullableValidateInvitationRequest struct {
	value *ValidateInvitationRequest
	isSet bool
}

func (v NullableValidateInvitationRequest) Get() *ValidateInvitationRequest {
	return v.value
}

func (v *NullableValidateInvitationRequest) Set(val *ValidateInvitationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateInvitationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateInvitationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateInvitationRequest(val *ValidateInvitationRequest) *NullableValidateInvitationRequest {
	return &NullableValidateInvitationRequest{value: val, isSet: true}
}

func (v NullableValidateInvitationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateInvitationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
