/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the MRBetaBashCodeExecutionOutputBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MRBetaBashCodeExecutionOutputBlock{}

// MRBetaBashCodeExecutionOutputBlock struct for MRBetaBashCodeExecutionOutputBlock
type MRBetaBashCodeExecutionOutputBlock struct {
	FileId               string `json:"file_id"`
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _MRBetaBashCodeExecutionOutputBlock MRBetaBashCodeExecutionOutputBlock

// NewMRBetaBashCodeExecutionOutputBlock instantiates a new MRBetaBashCodeExecutionOutputBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMRBetaBashCodeExecutionOutputBlock(fileId string, type_ string) *MRBetaBashCodeExecutionOutputBlock {
	this := MRBetaBashCodeExecutionOutputBlock{}
	this.FileId = fileId
	this.Type = type_
	return &this
}

// NewMRBetaBashCodeExecutionOutputBlockWithDefaults instantiates a new MRBetaBashCodeExecutionOutputBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMRBetaBashCodeExecutionOutputBlockWithDefaults() *MRBetaBashCodeExecutionOutputBlock {
	this := MRBetaBashCodeExecutionOutputBlock{}
	return &this
}

// GetFileId returns the FileId field value
func (o *MRBetaBashCodeExecutionOutputBlock) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *MRBetaBashCodeExecutionOutputBlock) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *MRBetaBashCodeExecutionOutputBlock) SetFileId(v string) {
	o.FileId = v
}

// GetType returns the Type field value
func (o *MRBetaBashCodeExecutionOutputBlock) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MRBetaBashCodeExecutionOutputBlock) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MRBetaBashCodeExecutionOutputBlock) SetType(v string) {
	o.Type = v
}

func (o MRBetaBashCodeExecutionOutputBlock) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MRBetaBashCodeExecutionOutputBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file_id"] = o.FileId
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MRBetaBashCodeExecutionOutputBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMRBetaBashCodeExecutionOutputBlock := _MRBetaBashCodeExecutionOutputBlock{}

	err = json.Unmarshal(data, &varMRBetaBashCodeExecutionOutputBlock)

	if err != nil {
		return err
	}

	*o = MRBetaBashCodeExecutionOutputBlock(varMRBetaBashCodeExecutionOutputBlock)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file_id")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMRBetaBashCodeExecutionOutputBlock struct {
	value *MRBetaBashCodeExecutionOutputBlock
	isSet bool
}

func (v NullableMRBetaBashCodeExecutionOutputBlock) Get() *MRBetaBashCodeExecutionOutputBlock {
	return v.value
}

func (v *NullableMRBetaBashCodeExecutionOutputBlock) Set(val *MRBetaBashCodeExecutionOutputBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableMRBetaBashCodeExecutionOutputBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableMRBetaBashCodeExecutionOutputBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMRBetaBashCodeExecutionOutputBlock(val *MRBetaBashCodeExecutionOutputBlock) *NullableMRBetaBashCodeExecutionOutputBlock {
	return &NullableMRBetaBashCodeExecutionOutputBlock{value: val, isSet: true}
}

func (v NullableMRBetaBashCodeExecutionOutputBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMRBetaBashCodeExecutionOutputBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
