/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PlaygroundMessageCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaygroundMessageCreate{}

// PlaygroundMessageCreate One turn in a transcript being saved.
type PlaygroundMessageCreate struct {
	Content   string         `json:"content"`
	Reasoning NullableString `json:"reasoning,omitempty"`
	Role      string         `json:"role"`
}

type _PlaygroundMessageCreate PlaygroundMessageCreate

// NewPlaygroundMessageCreate instantiates a new PlaygroundMessageCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaygroundMessageCreate(content string, role string) *PlaygroundMessageCreate {
	this := PlaygroundMessageCreate{}
	this.Content = content
	this.Role = role
	return &this
}

// NewPlaygroundMessageCreateWithDefaults instantiates a new PlaygroundMessageCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaygroundMessageCreateWithDefaults() *PlaygroundMessageCreate {
	this := PlaygroundMessageCreate{}
	return &this
}

// GetContent returns the Content field value
func (o *PlaygroundMessageCreate) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *PlaygroundMessageCreate) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *PlaygroundMessageCreate) SetContent(v string) {
	o.Content = v
}

// GetReasoning returns the Reasoning field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlaygroundMessageCreate) GetReasoning() string {
	if o == nil || IsNil(o.Reasoning.Get()) {
		var ret string
		return ret
	}
	return *o.Reasoning.Get()
}

// GetReasoningOk returns a tuple with the Reasoning field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlaygroundMessageCreate) GetReasoningOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reasoning.Get(), o.Reasoning.IsSet()
}

// HasReasoning returns a boolean if a field has been set.
func (o *PlaygroundMessageCreate) HasReasoning() bool {
	if o != nil && o.Reasoning.IsSet() {
		return true
	}

	return false
}

// SetReasoning gets a reference to the given NullableString and assigns it to the Reasoning field.
func (o *PlaygroundMessageCreate) SetReasoning(v string) {
	o.Reasoning.Set(&v)
}

// SetReasoningNil sets the value for Reasoning to be an explicit nil
func (o *PlaygroundMessageCreate) SetReasoningNil() {
	o.Reasoning.Set(nil)
}

// UnsetReasoning ensures that no value is present for Reasoning, not even an explicit nil
func (o *PlaygroundMessageCreate) UnsetReasoning() {
	o.Reasoning.Unset()
}

// GetRole returns the Role field value
func (o *PlaygroundMessageCreate) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *PlaygroundMessageCreate) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *PlaygroundMessageCreate) SetRole(v string) {
	o.Role = v
}

func (o PlaygroundMessageCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaygroundMessageCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	if o.Reasoning.IsSet() {
		toSerialize["reasoning"] = o.Reasoning.Get()
	}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *PlaygroundMessageCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaygroundMessageCreate := _PlaygroundMessageCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaygroundMessageCreate)

	if err != nil {
		return err
	}

	*o = PlaygroundMessageCreate(varPlaygroundMessageCreate)

	return err
}

type NullablePlaygroundMessageCreate struct {
	value *PlaygroundMessageCreate
	isSet bool
}

func (v NullablePlaygroundMessageCreate) Get() *PlaygroundMessageCreate {
	return v.value
}

func (v *NullablePlaygroundMessageCreate) Set(val *PlaygroundMessageCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaygroundMessageCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaygroundMessageCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaygroundMessageCreate(val *PlaygroundMessageCreate) *NullablePlaygroundMessageCreate {
	return &NullablePlaygroundMessageCreate{value: val, isSet: true}
}

func (v NullablePlaygroundMessageCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaygroundMessageCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
