/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.12.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the McpToolDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McpToolDefinition{}

// McpToolDefinition One live tool a caller-orchestrated application may expose to its model.  “annotations“ is the remote server's own metadata, passed through as untrusted data. Otari never turns “readOnlyHint“ into an authorization decision (R-RISK-1); each application owns its risk policy, and a server cannot waive an application's approval gate by labeling itself read-only.
type McpToolDefinition struct {
	// Provider-native request fields used as defaults (e.g. exa's 'type', searxng's 'engines').
	Annotations map[string]interface{} `json:"annotations,omitempty"`
	// The server's own description, untrusted.
	Description NullableString `json:"description,omitempty"`
	// The tool's MCP inputSchema, unmodified.
	InputSchema map[string]interface{} `json:"input_schema"`
	// The remote MCP tool name to send back to /api/v1/mcp/execute.
	Name string `json:"name"`
}

type _McpToolDefinition McpToolDefinition

// NewMcpToolDefinition instantiates a new McpToolDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpToolDefinition(inputSchema map[string]interface{}, name string) *McpToolDefinition {
	this := McpToolDefinition{}
	this.InputSchema = inputSchema
	this.Name = name
	return &this
}

// NewMcpToolDefinitionWithDefaults instantiates a new McpToolDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpToolDefinitionWithDefaults() *McpToolDefinition {
	this := McpToolDefinition{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *McpToolDefinition) GetAnnotations() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *McpToolDefinition) GetAnnotationsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Annotations) {
		return map[string]interface{}{}, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *McpToolDefinition) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]interface{} and assigns it to the Annotations field.
func (o *McpToolDefinition) SetAnnotations(v map[string]interface{}) {
	o.Annotations = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *McpToolDefinition) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *McpToolDefinition) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *McpToolDefinition) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *McpToolDefinition) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *McpToolDefinition) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *McpToolDefinition) UnsetDescription() {
	o.Description.Unset()
}

// GetInputSchema returns the InputSchema field value
func (o *McpToolDefinition) GetInputSchema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.InputSchema
}

// GetInputSchemaOk returns a tuple with the InputSchema field value
// and a boolean to check if the value has been set.
func (o *McpToolDefinition) GetInputSchemaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.InputSchema, true
}

// SetInputSchema sets field value
func (o *McpToolDefinition) SetInputSchema(v map[string]interface{}) {
	o.InputSchema = v
}

// GetName returns the Name field value
func (o *McpToolDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *McpToolDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *McpToolDefinition) SetName(v string) {
	o.Name = v
}

func (o McpToolDefinition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McpToolDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["input_schema"] = o.InputSchema
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *McpToolDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input_schema",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMcpToolDefinition := _McpToolDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMcpToolDefinition)

	if err != nil {
		return err
	}

	*o = McpToolDefinition(varMcpToolDefinition)

	return err
}

type NullableMcpToolDefinition struct {
	value *McpToolDefinition
	isSet bool
}

func (v NullableMcpToolDefinition) Get() *McpToolDefinition {
	return v.value
}

func (v *NullableMcpToolDefinition) Set(val *McpToolDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpToolDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpToolDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpToolDefinition(val *McpToolDefinition) *NullableMcpToolDefinition {
	return &NullableMcpToolDefinition{value: val, isSet: true}
}

func (v NullableMcpToolDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpToolDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
