/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the MRThinkingBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MRThinkingBlock{}

// MRThinkingBlock struct for MRThinkingBlock
type MRThinkingBlock struct {
	Signature            string `json:"signature"`
	Thinking             string `json:"thinking"`
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _MRThinkingBlock MRThinkingBlock

// NewMRThinkingBlock instantiates a new MRThinkingBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMRThinkingBlock(signature string, thinking string, type_ string) *MRThinkingBlock {
	this := MRThinkingBlock{}
	this.Signature = signature
	this.Thinking = thinking
	this.Type = type_
	return &this
}

// NewMRThinkingBlockWithDefaults instantiates a new MRThinkingBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMRThinkingBlockWithDefaults() *MRThinkingBlock {
	this := MRThinkingBlock{}
	return &this
}

// GetSignature returns the Signature field value
func (o *MRThinkingBlock) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *MRThinkingBlock) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *MRThinkingBlock) SetSignature(v string) {
	o.Signature = v
}

// GetThinking returns the Thinking field value
func (o *MRThinkingBlock) GetThinking() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thinking
}

// GetThinkingOk returns a tuple with the Thinking field value
// and a boolean to check if the value has been set.
func (o *MRThinkingBlock) GetThinkingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thinking, true
}

// SetThinking sets field value
func (o *MRThinkingBlock) SetThinking(v string) {
	o.Thinking = v
}

// GetType returns the Type field value
func (o *MRThinkingBlock) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MRThinkingBlock) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MRThinkingBlock) SetType(v string) {
	o.Type = v
}

func (o MRThinkingBlock) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MRThinkingBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signature"] = o.Signature
	toSerialize["thinking"] = o.Thinking
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MRThinkingBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signature",
		"thinking",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMRThinkingBlock := _MRThinkingBlock{}

	err = json.Unmarshal(data, &varMRThinkingBlock)

	if err != nil {
		return err
	}

	*o = MRThinkingBlock(varMRThinkingBlock)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "signature")
		delete(additionalProperties, "thinking")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMRThinkingBlock struct {
	value *MRThinkingBlock
	isSet bool
}

func (v NullableMRThinkingBlock) Get() *MRThinkingBlock {
	return v.value
}

func (v *NullableMRThinkingBlock) Set(val *MRThinkingBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableMRThinkingBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableMRThinkingBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMRThinkingBlock(val *MRThinkingBlock) *NullableMRThinkingBlock {
	return &NullableMRThinkingBlock{value: val, isSet: true}
}

func (v NullableMRThinkingBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMRThinkingBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
