/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MailSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailSettings{}

// MailSettings What this deployment can send, and what stands in the way if it cannot.
type MailSettings struct {
	// Whether a transport is configured at all.
	Enabled bool `json:"enabled"`
	// The 'From' address on outgoing mail, if one is configured.
	FromEmail NullableString `json:"from_email"`
	// The 'From' display name on outgoing mail.
	FromName string `json:"from_name"`
	// Settings that must be set before mail works, in config order. Empty exactly when 'ready' is true, so the dashboard can name what to configure rather than only reporting that mail is off.
	Missing []string `json:"missing"`
	// This deployment's own externally-reachable URL, used to build links in outgoing mail.
	PublicBaseUrl NullableString `json:"public_base_url"`
	// Whether a message carrying a link back to this deployment can be sent, which is what every message the control plane sends needs. Matches 'mail_ready' on /v1/bootstrap.
	Ready bool `json:"ready"`
	// The transport a send would use: 'smtp', 'console' (logged, not delivered), or 'none'.
	Transport string `json:"transport"`
}

type _MailSettings MailSettings

// NewMailSettings instantiates a new MailSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailSettings(enabled bool, fromEmail NullableString, fromName string, missing []string, publicBaseUrl NullableString, ready bool, transport string) *MailSettings {
	this := MailSettings{}
	this.Enabled = enabled
	this.FromEmail = fromEmail
	this.FromName = fromName
	this.Missing = missing
	this.PublicBaseUrl = publicBaseUrl
	this.Ready = ready
	this.Transport = transport
	return &this
}

// NewMailSettingsWithDefaults instantiates a new MailSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailSettingsWithDefaults() *MailSettings {
	this := MailSettings{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *MailSettings) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *MailSettings) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *MailSettings) SetEnabled(v bool) {
	o.Enabled = v
}

// GetFromEmail returns the FromEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *MailSettings) GetFromEmail() string {
	if o == nil || o.FromEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.FromEmail.Get()
}

// GetFromEmailOk returns a tuple with the FromEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailSettings) GetFromEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FromEmail.Get(), o.FromEmail.IsSet()
}

// SetFromEmail sets field value
func (o *MailSettings) SetFromEmail(v string) {
	o.FromEmail.Set(&v)
}

// GetFromName returns the FromName field value
func (o *MailSettings) GetFromName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value
// and a boolean to check if the value has been set.
func (o *MailSettings) GetFromNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromName, true
}

// SetFromName sets field value
func (o *MailSettings) SetFromName(v string) {
	o.FromName = v
}

// GetMissing returns the Missing field value
func (o *MailSettings) GetMissing() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Missing
}

// GetMissingOk returns a tuple with the Missing field value
// and a boolean to check if the value has been set.
func (o *MailSettings) GetMissingOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Missing, true
}

// SetMissing sets field value
func (o *MailSettings) SetMissing(v []string) {
	o.Missing = v
}

// GetPublicBaseUrl returns the PublicBaseUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *MailSettings) GetPublicBaseUrl() string {
	if o == nil || o.PublicBaseUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.PublicBaseUrl.Get()
}

// GetPublicBaseUrlOk returns a tuple with the PublicBaseUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailSettings) GetPublicBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublicBaseUrl.Get(), o.PublicBaseUrl.IsSet()
}

// SetPublicBaseUrl sets field value
func (o *MailSettings) SetPublicBaseUrl(v string) {
	o.PublicBaseUrl.Set(&v)
}

// GetReady returns the Ready field value
func (o *MailSettings) GetReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ready
}

// GetReadyOk returns a tuple with the Ready field value
// and a boolean to check if the value has been set.
func (o *MailSettings) GetReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ready, true
}

// SetReady sets field value
func (o *MailSettings) SetReady(v bool) {
	o.Ready = v
}

// GetTransport returns the Transport field value
func (o *MailSettings) GetTransport() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Transport
}

// GetTransportOk returns a tuple with the Transport field value
// and a boolean to check if the value has been set.
func (o *MailSettings) GetTransportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transport, true
}

// SetTransport sets field value
func (o *MailSettings) SetTransport(v string) {
	o.Transport = v
}

func (o MailSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["from_email"] = o.FromEmail.Get()
	toSerialize["from_name"] = o.FromName
	toSerialize["missing"] = o.Missing
	toSerialize["public_base_url"] = o.PublicBaseUrl.Get()
	toSerialize["ready"] = o.Ready
	toSerialize["transport"] = o.Transport
	return toSerialize, nil
}

func (o *MailSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"from_email",
		"from_name",
		"missing",
		"public_base_url",
		"ready",
		"transport",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailSettings := _MailSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailSettings)

	if err != nil {
		return err
	}

	*o = MailSettings(varMailSettings)

	return err
}

type NullableMailSettings struct {
	value *MailSettings
	isSet bool
}

func (v NullableMailSettings) Get() *MailSettings {
	return v.value
}

func (v *NullableMailSettings) Set(val *MailSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableMailSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableMailSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailSettings(val *MailSettings) *NullableMailSettings {
	return &NullableMailSettings{value: val, isSet: true}
}

func (v NullableMailSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
