/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Content14 struct for Content14
type Content14 struct {
	MRToolSearchToolResultError       *MRToolSearchToolResultError
	MRToolSearchToolSearchResultBlock *MRToolSearchToolSearchResultBlock
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Content14) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MRToolSearchToolResultError
	err = json.Unmarshal(data, &dst.MRToolSearchToolResultError)
	if err == nil {
		jsonMRToolSearchToolResultError, _ := json.Marshal(dst.MRToolSearchToolResultError)
		if string(jsonMRToolSearchToolResultError) == "{}" { // empty struct
			dst.MRToolSearchToolResultError = nil
		} else {
			return nil // data stored in dst.MRToolSearchToolResultError, return on the first match
		}
	} else {
		dst.MRToolSearchToolResultError = nil
	}

	// try to unmarshal JSON data into MRToolSearchToolSearchResultBlock
	err = json.Unmarshal(data, &dst.MRToolSearchToolSearchResultBlock)
	if err == nil {
		jsonMRToolSearchToolSearchResultBlock, _ := json.Marshal(dst.MRToolSearchToolSearchResultBlock)
		if string(jsonMRToolSearchToolSearchResultBlock) == "{}" { // empty struct
			dst.MRToolSearchToolSearchResultBlock = nil
		} else {
			return nil // data stored in dst.MRToolSearchToolSearchResultBlock, return on the first match
		}
	} else {
		dst.MRToolSearchToolSearchResultBlock = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Content14)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Content14) MarshalJSON() ([]byte, error) {
	if src.MRToolSearchToolResultError != nil {
		return json.Marshal(&src.MRToolSearchToolResultError)
	}

	if src.MRToolSearchToolSearchResultBlock != nil {
		return json.Marshal(&src.MRToolSearchToolSearchResultBlock)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableContent14 struct {
	value *Content14
	isSet bool
}

func (v NullableContent14) Get() *Content14 {
	return v.value
}

func (v *NullableContent14) Set(val *Content14) {
	v.value = val
	v.isSet = true
}

func (v NullableContent14) IsSet() bool {
	return v.isSet
}

func (v *NullableContent14) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent14(val *Content14) *NullableContent14 {
	return &NullableContent14{value: val, isSet: true}
}

func (v NullableContent14) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent14) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
