/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkspaceMcpServerPublic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceMcpServerPublic{}

// WorkspaceMcpServerPublic The API-facing shape. Never carries the token, only whether one is set.  No “last4“-style prefix either, unlike `OrgProviderKeyPublic`: a provider key's last four digits let an operator match a stored key against the one in their provider's console, and there is no equivalent workflow for an MCP bearer token.
type WorkspaceMcpServerPublic struct {
	AllowedTools []string       `json:"allowed_tools"`
	CreatedAt    string         `json:"created_at"`
	Enabled      bool           `json:"enabled"`
	HasToken     bool           `json:"has_token"`
	Id           string         `json:"id"`
	Name         string         `json:"name"`
	PurposeHint  NullableString `json:"purpose_hint"`
	UpdatedAt    string         `json:"updated_at"`
	Url          string         `json:"url"`
	WorkspaceId  string         `json:"workspace_id"`
}

type _WorkspaceMcpServerPublic WorkspaceMcpServerPublic

// NewWorkspaceMcpServerPublic instantiates a new WorkspaceMcpServerPublic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceMcpServerPublic(allowedTools []string, createdAt string, enabled bool, hasToken bool, id string, name string, purposeHint NullableString, updatedAt string, url string, workspaceId string) *WorkspaceMcpServerPublic {
	this := WorkspaceMcpServerPublic{}
	this.AllowedTools = allowedTools
	this.CreatedAt = createdAt
	this.Enabled = enabled
	this.HasToken = hasToken
	this.Id = id
	this.Name = name
	this.PurposeHint = purposeHint
	this.UpdatedAt = updatedAt
	this.Url = url
	this.WorkspaceId = workspaceId
	return &this
}

// NewWorkspaceMcpServerPublicWithDefaults instantiates a new WorkspaceMcpServerPublic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceMcpServerPublicWithDefaults() *WorkspaceMcpServerPublic {
	this := WorkspaceMcpServerPublic{}
	return &this
}

// GetAllowedTools returns the AllowedTools field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *WorkspaceMcpServerPublic) GetAllowedTools() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedTools
}

// GetAllowedToolsOk returns a tuple with the AllowedTools field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceMcpServerPublic) GetAllowedToolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedTools) {
		return nil, false
	}
	return o.AllowedTools, true
}

// SetAllowedTools sets field value
func (o *WorkspaceMcpServerPublic) SetAllowedTools(v []string) {
	o.AllowedTools = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WorkspaceMcpServerPublic) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WorkspaceMcpServerPublic) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetEnabled returns the Enabled field value
func (o *WorkspaceMcpServerPublic) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *WorkspaceMcpServerPublic) SetEnabled(v bool) {
	o.Enabled = v
}

// GetHasToken returns the HasToken field value
func (o *WorkspaceMcpServerPublic) GetHasToken() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasToken
}

// GetHasTokenOk returns a tuple with the HasToken field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetHasTokenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasToken, true
}

// SetHasToken sets field value
func (o *WorkspaceMcpServerPublic) SetHasToken(v bool) {
	o.HasToken = v
}

// GetId returns the Id field value
func (o *WorkspaceMcpServerPublic) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkspaceMcpServerPublic) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WorkspaceMcpServerPublic) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspaceMcpServerPublic) SetName(v string) {
	o.Name = v
}

// GetPurposeHint returns the PurposeHint field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkspaceMcpServerPublic) GetPurposeHint() string {
	if o == nil || o.PurposeHint.Get() == nil {
		var ret string
		return ret
	}

	return *o.PurposeHint.Get()
}

// GetPurposeHintOk returns a tuple with the PurposeHint field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceMcpServerPublic) GetPurposeHintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurposeHint.Get(), o.PurposeHint.IsSet()
}

// SetPurposeHint sets field value
func (o *WorkspaceMcpServerPublic) SetPurposeHint(v string) {
	o.PurposeHint.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WorkspaceMcpServerPublic) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WorkspaceMcpServerPublic) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *WorkspaceMcpServerPublic) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WorkspaceMcpServerPublic) SetUrl(v string) {
	o.Url = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *WorkspaceMcpServerPublic) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMcpServerPublic) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *WorkspaceMcpServerPublic) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

func (o WorkspaceMcpServerPublic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceMcpServerPublic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedTools != nil {
		toSerialize["allowed_tools"] = o.AllowedTools
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["enabled"] = o.Enabled
	toSerialize["has_token"] = o.HasToken
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["purpose_hint"] = o.PurposeHint.Get()
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	toSerialize["workspace_id"] = o.WorkspaceId
	return toSerialize, nil
}

func (o *WorkspaceMcpServerPublic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowed_tools",
		"created_at",
		"enabled",
		"has_token",
		"id",
		"name",
		"purpose_hint",
		"updated_at",
		"url",
		"workspace_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceMcpServerPublic := _WorkspaceMcpServerPublic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceMcpServerPublic)

	if err != nil {
		return err
	}

	*o = WorkspaceMcpServerPublic(varWorkspaceMcpServerPublic)

	return err
}

type NullableWorkspaceMcpServerPublic struct {
	value *WorkspaceMcpServerPublic
	isSet bool
}

func (v NullableWorkspaceMcpServerPublic) Get() *WorkspaceMcpServerPublic {
	return v.value
}

func (v *NullableWorkspaceMcpServerPublic) Set(val *WorkspaceMcpServerPublic) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceMcpServerPublic) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceMcpServerPublic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceMcpServerPublic(val *WorkspaceMcpServerPublic) *NullableWorkspaceMcpServerPublic {
	return &NullableWorkspaceMcpServerPublic{value: val, isSet: true}
}

func (v NullableWorkspaceMcpServerPublic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceMcpServerPublic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
