/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Content11 struct for Content11
type Content11 struct {
	MRBetaWebSearchToolResultError    *MRBetaWebSearchToolResultError
	ArrayOfMRBetaWebSearchResultBlock *[]MRBetaWebSearchResultBlock
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Content11) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MRBetaWebSearchToolResultError
	err = json.Unmarshal(data, &dst.MRBetaWebSearchToolResultError)
	if err == nil {
		jsonMRBetaWebSearchToolResultError, _ := json.Marshal(dst.MRBetaWebSearchToolResultError)
		if string(jsonMRBetaWebSearchToolResultError) == "{}" { // empty struct
			dst.MRBetaWebSearchToolResultError = nil
		} else {
			return nil // data stored in dst.MRBetaWebSearchToolResultError, return on the first match
		}
	} else {
		dst.MRBetaWebSearchToolResultError = nil
	}

	// try to unmarshal JSON data into ArrayOfMRBetaWebSearchResultBlock
	err = json.Unmarshal(data, &dst.ArrayOfMRBetaWebSearchResultBlock)
	if err == nil {
		jsonArrayOfMRBetaWebSearchResultBlock, _ := json.Marshal(dst.ArrayOfMRBetaWebSearchResultBlock)
		if string(jsonArrayOfMRBetaWebSearchResultBlock) == "{}" { // empty struct
			dst.ArrayOfMRBetaWebSearchResultBlock = nil
		} else {
			return nil // data stored in dst.ArrayOfMRBetaWebSearchResultBlock, return on the first match
		}
	} else {
		dst.ArrayOfMRBetaWebSearchResultBlock = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Content11)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Content11) MarshalJSON() ([]byte, error) {
	if src.MRBetaWebSearchToolResultError != nil {
		return json.Marshal(&src.MRBetaWebSearchToolResultError)
	}

	if src.ArrayOfMRBetaWebSearchResultBlock != nil {
		return json.Marshal(&src.ArrayOfMRBetaWebSearchResultBlock)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableContent11 struct {
	value *Content11
	isSet bool
}

func (v NullableContent11) Get() *Content11 {
	return v.value
}

func (v *NullableContent11) Set(val *Content11) {
	v.value = val
	v.isSet = true
}

func (v NullableContent11) IsSet() bool {
	return v.isSet
}

func (v *NullableContent11) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent11(val *Content11) *NullableContent11 {
	return &NullableContent11{value: val, isSet: true}
}

func (v NullableContent11) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent11) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
