/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RateLimitRulesPublic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitRulesPublic{}

// RateLimitRulesPublic Every rule in effect: config-file rules first, then stored ones, each in name order.
type RateLimitRulesPublic struct {
	Rules []RateLimitRulePublic `json:"rules"`
}

type _RateLimitRulesPublic RateLimitRulesPublic

// NewRateLimitRulesPublic instantiates a new RateLimitRulesPublic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitRulesPublic(rules []RateLimitRulePublic) *RateLimitRulesPublic {
	this := RateLimitRulesPublic{}
	this.Rules = rules
	return &this
}

// NewRateLimitRulesPublicWithDefaults instantiates a new RateLimitRulesPublic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitRulesPublicWithDefaults() *RateLimitRulesPublic {
	this := RateLimitRulesPublic{}
	return &this
}

// GetRules returns the Rules field value
func (o *RateLimitRulesPublic) GetRules() []RateLimitRulePublic {
	if o == nil {
		var ret []RateLimitRulePublic
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *RateLimitRulesPublic) GetRulesOk() ([]RateLimitRulePublic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *RateLimitRulesPublic) SetRules(v []RateLimitRulePublic) {
	o.Rules = v
}

func (o RateLimitRulesPublic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitRulesPublic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rules"] = o.Rules
	return toSerialize, nil
}

func (o *RateLimitRulesPublic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRateLimitRulesPublic := _RateLimitRulesPublic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRateLimitRulesPublic)

	if err != nil {
		return err
	}

	*o = RateLimitRulesPublic(varRateLimitRulesPublic)

	return err
}

type NullableRateLimitRulesPublic struct {
	value *RateLimitRulesPublic
	isSet bool
}

func (v NullableRateLimitRulesPublic) Get() *RateLimitRulesPublic {
	return v.value
}

func (v *NullableRateLimitRulesPublic) Set(val *RateLimitRulesPublic) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitRulesPublic) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitRulesPublic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitRulesPublic(val *RateLimitRulesPublic) *NullableRateLimitRulesPublic {
	return &NullableRateLimitRulesPublic{value: val, isSet: true}
}

func (v NullableRateLimitRulesPublic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitRulesPublic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
