/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LearnedPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LearnedPolicy{}

// LearnedPolicy A policy whose selection depends on routing memory, for the status overview.  Only a *learned* policy belongs here. A weighted policy names a router too, but its split is written in the policy document, so listing it under a warmth report would tie it to a pool it never reads.
type LearnedPolicy struct {
	Backend       string   `json:"backend"`
	Candidates    []string `json:"candidates"`
	DefaultTarget string   `json:"default_target"`
	Name          string   `json:"name"`
}

type _LearnedPolicy LearnedPolicy

// NewLearnedPolicy instantiates a new LearnedPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLearnedPolicy(backend string, candidates []string, defaultTarget string, name string) *LearnedPolicy {
	this := LearnedPolicy{}
	this.Backend = backend
	this.Candidates = candidates
	this.DefaultTarget = defaultTarget
	this.Name = name
	return &this
}

// NewLearnedPolicyWithDefaults instantiates a new LearnedPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLearnedPolicyWithDefaults() *LearnedPolicy {
	this := LearnedPolicy{}
	return &this
}

// GetBackend returns the Backend field value
func (o *LearnedPolicy) GetBackend() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Backend
}

// GetBackendOk returns a tuple with the Backend field value
// and a boolean to check if the value has been set.
func (o *LearnedPolicy) GetBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backend, true
}

// SetBackend sets field value
func (o *LearnedPolicy) SetBackend(v string) {
	o.Backend = v
}

// GetCandidates returns the Candidates field value
func (o *LearnedPolicy) GetCandidates() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Candidates
}

// GetCandidatesOk returns a tuple with the Candidates field value
// and a boolean to check if the value has been set.
func (o *LearnedPolicy) GetCandidatesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Candidates, true
}

// SetCandidates sets field value
func (o *LearnedPolicy) SetCandidates(v []string) {
	o.Candidates = v
}

// GetDefaultTarget returns the DefaultTarget field value
func (o *LearnedPolicy) GetDefaultTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultTarget
}

// GetDefaultTargetOk returns a tuple with the DefaultTarget field value
// and a boolean to check if the value has been set.
func (o *LearnedPolicy) GetDefaultTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultTarget, true
}

// SetDefaultTarget sets field value
func (o *LearnedPolicy) SetDefaultTarget(v string) {
	o.DefaultTarget = v
}

// GetName returns the Name field value
func (o *LearnedPolicy) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LearnedPolicy) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LearnedPolicy) SetName(v string) {
	o.Name = v
}

func (o LearnedPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LearnedPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backend"] = o.Backend
	toSerialize["candidates"] = o.Candidates
	toSerialize["default_target"] = o.DefaultTarget
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *LearnedPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backend",
		"candidates",
		"default_target",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLearnedPolicy := _LearnedPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLearnedPolicy)

	if err != nil {
		return err
	}

	*o = LearnedPolicy(varLearnedPolicy)

	return err
}

type NullableLearnedPolicy struct {
	value *LearnedPolicy
	isSet bool
}

func (v NullableLearnedPolicy) Get() *LearnedPolicy {
	return v.value
}

func (v *NullableLearnedPolicy) Set(val *LearnedPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableLearnedPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableLearnedPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLearnedPolicy(val *LearnedPolicy) *NullableLearnedPolicy {
	return &NullableLearnedPolicy{value: val, isSet: true}
}

func (v NullableLearnedPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLearnedPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
