/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendTestMailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendTestMailRequest{}

// SendTestMailRequest Where to send the test message.
type SendTestMailRequest struct {
	// Recipient of the test message.
	To string `json:"to"`
}

type _SendTestMailRequest SendTestMailRequest

// NewSendTestMailRequest instantiates a new SendTestMailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendTestMailRequest(to string) *SendTestMailRequest {
	this := SendTestMailRequest{}
	this.To = to
	return &this
}

// NewSendTestMailRequestWithDefaults instantiates a new SendTestMailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendTestMailRequestWithDefaults() *SendTestMailRequest {
	this := SendTestMailRequest{}
	return &this
}

// GetTo returns the To field value
func (o *SendTestMailRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SendTestMailRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *SendTestMailRequest) SetTo(v string) {
	o.To = v
}

func (o SendTestMailRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendTestMailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *SendTestMailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendTestMailRequest := _SendTestMailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendTestMailRequest)

	if err != nil {
		return err
	}

	*o = SendTestMailRequest(varSendTestMailRequest)

	return err
}

type NullableSendTestMailRequest struct {
	value *SendTestMailRequest
	isSet bool
}

func (v NullableSendTestMailRequest) Get() *SendTestMailRequest {
	return v.value
}

func (v *NullableSendTestMailRequest) Set(val *SendTestMailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendTestMailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendTestMailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendTestMailRequest(val *SendTestMailRequest) *NullableSendTestMailRequest {
	return &NullableSendTestMailRequest{value: val, isSet: true}
}

func (v NullableSendTestMailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendTestMailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
