/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ModerationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModerationRequest{}

// ModerationRequest OpenAI-compatible moderation request.
type ModerationRequest struct {
	Input Input1         `json:"input"`
	Model string         `json:"model"`
	User  NullableString `json:"user,omitempty"`
}

type _ModerationRequest ModerationRequest

// NewModerationRequest instantiates a new ModerationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModerationRequest(input Input1, model string) *ModerationRequest {
	this := ModerationRequest{}
	this.Input = input
	this.Model = model
	return &this
}

// NewModerationRequestWithDefaults instantiates a new ModerationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModerationRequestWithDefaults() *ModerationRequest {
	this := ModerationRequest{}
	return &this
}

// GetInput returns the Input field value
func (o *ModerationRequest) GetInput() Input1 {
	if o == nil {
		var ret Input1
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *ModerationRequest) GetInputOk() (*Input1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *ModerationRequest) SetInput(v Input1) {
	o.Input = v
}

// GetModel returns the Model field value
func (o *ModerationRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ModerationRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ModerationRequest) SetModel(v string) {
	o.Model = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModerationRequest) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModerationRequest) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *ModerationRequest) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *ModerationRequest) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *ModerationRequest) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *ModerationRequest) UnsetUser() {
	o.User.Unset()
}

func (o ModerationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModerationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	toSerialize["model"] = o.Model
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	return toSerialize, nil
}

func (o *ModerationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
		"model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModerationRequest := _ModerationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModerationRequest)

	if err != nil {
		return err
	}

	*o = ModerationRequest(varModerationRequest)

	return err
}

type NullableModerationRequest struct {
	value *ModerationRequest
	isSet bool
}

func (v NullableModerationRequest) Get() *ModerationRequest {
	return v.value
}

func (v *NullableModerationRequest) Set(val *ModerationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModerationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModerationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModerationRequest(val *ModerationRequest) *NullableModerationRequest {
	return &NullableModerationRequest{value: val, isSet: true}
}

func (v NullableModerationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModerationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
