/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ActiveOrganizationMembersPublic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActiveOrganizationMembersPublic{}

// ActiveOrganizationMembersPublic struct for ActiveOrganizationMembersPublic
type ActiveOrganizationMembersPublic struct {
	Count int32                            `json:"count"`
	Data  []ActiveOrganizationMemberPublic `json:"data"`
}

type _ActiveOrganizationMembersPublic ActiveOrganizationMembersPublic

// NewActiveOrganizationMembersPublic instantiates a new ActiveOrganizationMembersPublic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveOrganizationMembersPublic(count int32, data []ActiveOrganizationMemberPublic) *ActiveOrganizationMembersPublic {
	this := ActiveOrganizationMembersPublic{}
	this.Count = count
	this.Data = data
	return &this
}

// NewActiveOrganizationMembersPublicWithDefaults instantiates a new ActiveOrganizationMembersPublic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveOrganizationMembersPublicWithDefaults() *ActiveOrganizationMembersPublic {
	this := ActiveOrganizationMembersPublic{}
	return &this
}

// GetCount returns the Count field value
func (o *ActiveOrganizationMembersPublic) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ActiveOrganizationMembersPublic) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ActiveOrganizationMembersPublic) SetCount(v int32) {
	o.Count = v
}

// GetData returns the Data field value
func (o *ActiveOrganizationMembersPublic) GetData() []ActiveOrganizationMemberPublic {
	if o == nil {
		var ret []ActiveOrganizationMemberPublic
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ActiveOrganizationMembersPublic) GetDataOk() ([]ActiveOrganizationMemberPublic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ActiveOrganizationMembersPublic) SetData(v []ActiveOrganizationMemberPublic) {
	o.Data = v
}

func (o ActiveOrganizationMembersPublic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActiveOrganizationMembersPublic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ActiveOrganizationMembersPublic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActiveOrganizationMembersPublic := _ActiveOrganizationMembersPublic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActiveOrganizationMembersPublic)

	if err != nil {
		return err
	}

	*o = ActiveOrganizationMembersPublic(varActiveOrganizationMembersPublic)

	return err
}

type NullableActiveOrganizationMembersPublic struct {
	value *ActiveOrganizationMembersPublic
	isSet bool
}

func (v NullableActiveOrganizationMembersPublic) Get() *ActiveOrganizationMembersPublic {
	return v.value
}

func (v *NullableActiveOrganizationMembersPublic) Set(val *ActiveOrganizationMembersPublic) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveOrganizationMembersPublic) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveOrganizationMembersPublic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveOrganizationMembersPublic(val *ActiveOrganizationMembersPublic) *NullableActiveOrganizationMembersPublic {
	return &NullableActiveOrganizationMembersPublic{value: val, isSet: true}
}

func (v NullableActiveOrganizationMembersPublic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveOrganizationMembersPublic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
