/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecordedPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordedPool{}

// RecordedPool How warm one pool is after the write.
type RecordedPool struct {
	Records int32          `json:"records"`
	TaskId  NullableString `json:"task_id"`
	Warm    bool           `json:"warm"`
}

type _RecordedPool RecordedPool

// NewRecordedPool instantiates a new RecordedPool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordedPool(records int32, taskId NullableString, warm bool) *RecordedPool {
	this := RecordedPool{}
	this.Records = records
	this.TaskId = taskId
	this.Warm = warm
	return &this
}

// NewRecordedPoolWithDefaults instantiates a new RecordedPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordedPoolWithDefaults() *RecordedPool {
	this := RecordedPool{}
	return &this
}

// GetRecords returns the Records field value
func (o *RecordedPool) GetRecords() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *RecordedPool) GetRecordsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Records, true
}

// SetRecords sets field value
func (o *RecordedPool) SetRecords(v int32) {
	o.Records = v
}

// GetTaskId returns the TaskId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RecordedPool) GetTaskId() string {
	if o == nil || o.TaskId.Get() == nil {
		var ret string
		return ret
	}

	return *o.TaskId.Get()
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordedPool) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskId.Get(), o.TaskId.IsSet()
}

// SetTaskId sets field value
func (o *RecordedPool) SetTaskId(v string) {
	o.TaskId.Set(&v)
}

// GetWarm returns the Warm field value
func (o *RecordedPool) GetWarm() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Warm
}

// GetWarmOk returns a tuple with the Warm field value
// and a boolean to check if the value has been set.
func (o *RecordedPool) GetWarmOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Warm, true
}

// SetWarm sets field value
func (o *RecordedPool) SetWarm(v bool) {
	o.Warm = v
}

func (o RecordedPool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordedPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	toSerialize["task_id"] = o.TaskId.Get()
	toSerialize["warm"] = o.Warm
	return toSerialize, nil
}

func (o *RecordedPool) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
		"task_id",
		"warm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordedPool := _RecordedPool{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordedPool)

	if err != nil {
		return err
	}

	*o = RecordedPool(varRecordedPool)

	return err
}

type NullableRecordedPool struct {
	value *RecordedPool
	isSet bool
}

func (v NullableRecordedPool) Get() *RecordedPool {
	return v.value
}

func (v *NullableRecordedPool) Set(val *RecordedPool) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordedPool) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordedPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordedPool(val *RecordedPool) *NullableRecordedPool {
	return &NullableRecordedPool{value: val, isSet: true}
}

func (v NullableRecordedPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordedPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
