/*
otari-gateway

A clean FastAPI gateway for otari with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Content7 struct for Content7
type Content7 struct {
	MRWebFetchBlock                *MRWebFetchBlock
	MRWebFetchToolResultErrorBlock *MRWebFetchToolResultErrorBlock
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Content7) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MRWebFetchBlock
	err = json.Unmarshal(data, &dst.MRWebFetchBlock)
	if err == nil {
		jsonMRWebFetchBlock, _ := json.Marshal(dst.MRWebFetchBlock)
		if string(jsonMRWebFetchBlock) == "{}" { // empty struct
			dst.MRWebFetchBlock = nil
		} else {
			return nil // data stored in dst.MRWebFetchBlock, return on the first match
		}
	} else {
		dst.MRWebFetchBlock = nil
	}

	// try to unmarshal JSON data into MRWebFetchToolResultErrorBlock
	err = json.Unmarshal(data, &dst.MRWebFetchToolResultErrorBlock)
	if err == nil {
		jsonMRWebFetchToolResultErrorBlock, _ := json.Marshal(dst.MRWebFetchToolResultErrorBlock)
		if string(jsonMRWebFetchToolResultErrorBlock) == "{}" { // empty struct
			dst.MRWebFetchToolResultErrorBlock = nil
		} else {
			return nil // data stored in dst.MRWebFetchToolResultErrorBlock, return on the first match
		}
	} else {
		dst.MRWebFetchToolResultErrorBlock = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Content7)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Content7) MarshalJSON() ([]byte, error) {
	if src.MRWebFetchBlock != nil {
		return json.Marshal(&src.MRWebFetchBlock)
	}

	if src.MRWebFetchToolResultErrorBlock != nil {
		return json.Marshal(&src.MRWebFetchToolResultErrorBlock)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableContent7 struct {
	value *Content7
	isSet bool
}

func (v NullableContent7) Get() *Content7 {
	return v.value
}

func (v *NullableContent7) Set(val *Content7) {
	v.value = val
	v.isSet = true
}

func (v NullableContent7) IsSet() bool {
	return v.isSet
}

func (v *NullableContent7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent7(val *Content7) *NullableContent7 {
	return &NullableContent7{value: val, isSet: true}
}

func (v NullableContent7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
