/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OrgProviderKeysPublic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgProviderKeysPublic{}

// OrgProviderKeysPublic struct for OrgProviderKeysPublic
type OrgProviderKeysPublic struct {
	Count int32                  `json:"count"`
	Data  []OrgProviderKeyPublic `json:"data"`
}

type _OrgProviderKeysPublic OrgProviderKeysPublic

// NewOrgProviderKeysPublic instantiates a new OrgProviderKeysPublic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgProviderKeysPublic(count int32, data []OrgProviderKeyPublic) *OrgProviderKeysPublic {
	this := OrgProviderKeysPublic{}
	this.Count = count
	this.Data = data
	return &this
}

// NewOrgProviderKeysPublicWithDefaults instantiates a new OrgProviderKeysPublic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgProviderKeysPublicWithDefaults() *OrgProviderKeysPublic {
	this := OrgProviderKeysPublic{}
	return &this
}

// GetCount returns the Count field value
func (o *OrgProviderKeysPublic) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *OrgProviderKeysPublic) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *OrgProviderKeysPublic) SetCount(v int32) {
	o.Count = v
}

// GetData returns the Data field value
func (o *OrgProviderKeysPublic) GetData() []OrgProviderKeyPublic {
	if o == nil {
		var ret []OrgProviderKeyPublic
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OrgProviderKeysPublic) GetDataOk() ([]OrgProviderKeyPublic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *OrgProviderKeysPublic) SetData(v []OrgProviderKeyPublic) {
	o.Data = v
}

func (o OrgProviderKeysPublic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgProviderKeysPublic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *OrgProviderKeysPublic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgProviderKeysPublic := _OrgProviderKeysPublic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgProviderKeysPublic)

	if err != nil {
		return err
	}

	*o = OrgProviderKeysPublic(varOrgProviderKeysPublic)

	return err
}

type NullableOrgProviderKeysPublic struct {
	value *OrgProviderKeysPublic
	isSet bool
}

func (v NullableOrgProviderKeysPublic) Get() *OrgProviderKeysPublic {
	return v.value
}

func (v *NullableOrgProviderKeysPublic) Set(val *OrgProviderKeysPublic) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgProviderKeysPublic) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgProviderKeysPublic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgProviderKeysPublic(val *OrgProviderKeysPublic) *NullableOrgProviderKeysPublic {
	return &NullableOrgProviderKeysPublic{value: val, isSet: true}
}

func (v NullableOrgProviderKeysPublic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgProviderKeysPublic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
