/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the MRBetaCacheMissToolsChanged type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MRBetaCacheMissToolsChanged{}

// MRBetaCacheMissToolsChanged struct for MRBetaCacheMissToolsChanged
type MRBetaCacheMissToolsChanged struct {
	CacheMissedInputTokens int32  `json:"cache_missed_input_tokens"`
	Type                   string `json:"type"`
	AdditionalProperties   map[string]interface{}
}

type _MRBetaCacheMissToolsChanged MRBetaCacheMissToolsChanged

// NewMRBetaCacheMissToolsChanged instantiates a new MRBetaCacheMissToolsChanged object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMRBetaCacheMissToolsChanged(cacheMissedInputTokens int32, type_ string) *MRBetaCacheMissToolsChanged {
	this := MRBetaCacheMissToolsChanged{}
	this.CacheMissedInputTokens = cacheMissedInputTokens
	this.Type = type_
	return &this
}

// NewMRBetaCacheMissToolsChangedWithDefaults instantiates a new MRBetaCacheMissToolsChanged object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMRBetaCacheMissToolsChangedWithDefaults() *MRBetaCacheMissToolsChanged {
	this := MRBetaCacheMissToolsChanged{}
	return &this
}

// GetCacheMissedInputTokens returns the CacheMissedInputTokens field value
func (o *MRBetaCacheMissToolsChanged) GetCacheMissedInputTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CacheMissedInputTokens
}

// GetCacheMissedInputTokensOk returns a tuple with the CacheMissedInputTokens field value
// and a boolean to check if the value has been set.
func (o *MRBetaCacheMissToolsChanged) GetCacheMissedInputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CacheMissedInputTokens, true
}

// SetCacheMissedInputTokens sets field value
func (o *MRBetaCacheMissToolsChanged) SetCacheMissedInputTokens(v int32) {
	o.CacheMissedInputTokens = v
}

// GetType returns the Type field value
func (o *MRBetaCacheMissToolsChanged) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MRBetaCacheMissToolsChanged) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MRBetaCacheMissToolsChanged) SetType(v string) {
	o.Type = v
}

func (o MRBetaCacheMissToolsChanged) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MRBetaCacheMissToolsChanged) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cache_missed_input_tokens"] = o.CacheMissedInputTokens
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MRBetaCacheMissToolsChanged) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cache_missed_input_tokens",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMRBetaCacheMissToolsChanged := _MRBetaCacheMissToolsChanged{}

	err = json.Unmarshal(data, &varMRBetaCacheMissToolsChanged)

	if err != nil {
		return err
	}

	*o = MRBetaCacheMissToolsChanged(varMRBetaCacheMissToolsChanged)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cache_missed_input_tokens")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMRBetaCacheMissToolsChanged struct {
	value *MRBetaCacheMissToolsChanged
	isSet bool
}

func (v NullableMRBetaCacheMissToolsChanged) Get() *MRBetaCacheMissToolsChanged {
	return v.value
}

func (v *NullableMRBetaCacheMissToolsChanged) Set(val *MRBetaCacheMissToolsChanged) {
	v.value = val
	v.isSet = true
}

func (v NullableMRBetaCacheMissToolsChanged) IsSet() bool {
	return v.isSet
}

func (v *NullableMRBetaCacheMissToolsChanged) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMRBetaCacheMissToolsChanged(val *MRBetaCacheMissToolsChanged) *NullableMRBetaCacheMissToolsChanged {
	return &NullableMRBetaCacheMissToolsChanged{value: val, isSet: true}
}

func (v NullableMRBetaCacheMissToolsChanged) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMRBetaCacheMissToolsChanged) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
