/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the PricingRefreshConfirmationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricingRefreshConfirmationResponse{}

// PricingRefreshConfirmationResponse Result of activating a reviewed genai-prices refresh.
type PricingRefreshConfirmationResponse struct {
	Applied *bool `json:"applied,omitempty"`
}

// NewPricingRefreshConfirmationResponse instantiates a new PricingRefreshConfirmationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricingRefreshConfirmationResponse() *PricingRefreshConfirmationResponse {
	this := PricingRefreshConfirmationResponse{}
	var applied bool = true
	this.Applied = &applied
	return &this
}

// NewPricingRefreshConfirmationResponseWithDefaults instantiates a new PricingRefreshConfirmationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricingRefreshConfirmationResponseWithDefaults() *PricingRefreshConfirmationResponse {
	this := PricingRefreshConfirmationResponse{}
	var applied bool = true
	this.Applied = &applied
	return &this
}

// GetApplied returns the Applied field value if set, zero value otherwise.
func (o *PricingRefreshConfirmationResponse) GetApplied() bool {
	if o == nil || IsNil(o.Applied) {
		var ret bool
		return ret
	}
	return *o.Applied
}

// GetAppliedOk returns a tuple with the Applied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingRefreshConfirmationResponse) GetAppliedOk() (*bool, bool) {
	if o == nil || IsNil(o.Applied) {
		return nil, false
	}
	return o.Applied, true
}

// HasApplied returns a boolean if a field has been set.
func (o *PricingRefreshConfirmationResponse) HasApplied() bool {
	if o != nil && !IsNil(o.Applied) {
		return true
	}

	return false
}

// SetApplied gets a reference to the given bool and assigns it to the Applied field.
func (o *PricingRefreshConfirmationResponse) SetApplied(v bool) {
	o.Applied = &v
}

func (o PricingRefreshConfirmationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricingRefreshConfirmationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Applied) {
		toSerialize["applied"] = o.Applied
	}
	return toSerialize, nil
}

type NullablePricingRefreshConfirmationResponse struct {
	value *PricingRefreshConfirmationResponse
	isSet bool
}

func (v NullablePricingRefreshConfirmationResponse) Get() *PricingRefreshConfirmationResponse {
	return v.value
}

func (v *NullablePricingRefreshConfirmationResponse) Set(val *PricingRefreshConfirmationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePricingRefreshConfirmationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePricingRefreshConfirmationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricingRefreshConfirmationResponse(val *PricingRefreshConfirmationResponse) *NullablePricingRefreshConfirmationResponse {
	return &NullablePricingRefreshConfirmationResponse{value: val, isSet: true}
}

func (v NullablePricingRefreshConfirmationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricingRefreshConfirmationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
