/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendTestMailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendTestMailResponse{}

// SendTestMailResponse The outcome of one test send.  “reason“ carries the transport's own error text, which is the whole value of a test button (an operator needs to know it was a refused login rather than a wrong port). Safe here and only here: this endpoint is master-key gated, unlike the public error paths that must not leak internals.
type SendTestMailResponse struct {
	Ok        bool           `json:"ok"`
	Reason    NullableString `json:"reason,omitempty"`
	Transport string         `json:"transport"`
}

type _SendTestMailResponse SendTestMailResponse

// NewSendTestMailResponse instantiates a new SendTestMailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendTestMailResponse(ok bool, transport string) *SendTestMailResponse {
	this := SendTestMailResponse{}
	this.Ok = ok
	this.Transport = transport
	return &this
}

// NewSendTestMailResponseWithDefaults instantiates a new SendTestMailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendTestMailResponseWithDefaults() *SendTestMailResponse {
	this := SendTestMailResponse{}
	return &this
}

// GetOk returns the Ok field value
func (o *SendTestMailResponse) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *SendTestMailResponse) GetOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *SendTestMailResponse) SetOk(v bool) {
	o.Ok = v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendTestMailResponse) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendTestMailResponse) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *SendTestMailResponse) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *SendTestMailResponse) SetReason(v string) {
	o.Reason.Set(&v)
}

// SetReasonNil sets the value for Reason to be an explicit nil
func (o *SendTestMailResponse) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *SendTestMailResponse) UnsetReason() {
	o.Reason.Unset()
}

// GetTransport returns the Transport field value
func (o *SendTestMailResponse) GetTransport() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Transport
}

// GetTransportOk returns a tuple with the Transport field value
// and a boolean to check if the value has been set.
func (o *SendTestMailResponse) GetTransportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transport, true
}

// SetTransport sets field value
func (o *SendTestMailResponse) SetTransport(v string) {
	o.Transport = v
}

func (o SendTestMailResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendTestMailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ok"] = o.Ok
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	toSerialize["transport"] = o.Transport
	return toSerialize, nil
}

func (o *SendTestMailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ok",
		"transport",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendTestMailResponse := _SendTestMailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendTestMailResponse)

	if err != nil {
		return err
	}

	*o = SendTestMailResponse(varSendTestMailResponse)

	return err
}

type NullableSendTestMailResponse struct {
	value *SendTestMailResponse
	isSet bool
}

func (v NullableSendTestMailResponse) Get() *SendTestMailResponse {
	return v.value
}

func (v *NullableSendTestMailResponse) Set(val *SendTestMailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendTestMailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendTestMailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendTestMailResponse(val *SendTestMailResponse) *NullableSendTestMailResponse {
	return &NullableSendTestMailResponse{value: val, isSet: true}
}

func (v NullableSendTestMailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendTestMailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
