/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProviderCapabilitiesSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderCapabilitiesSchema{}

// ProviderCapabilitiesSchema Curated capability flags for a provider.
type ProviderCapabilitiesSchema struct {
	Audio           bool `json:"audio"`
	Embeddings      bool `json:"embeddings"`
	ImageGeneration bool `json:"image_generation"`
	ListModels      bool `json:"list_models"`
	Moderation      bool `json:"moderation"`
	Pdf             bool `json:"pdf"`
	Reasoning       bool `json:"reasoning"`
	Rerank          bool `json:"rerank"`
	ResponsesApi    bool `json:"responses_api"`
	Streaming       bool `json:"streaming"`
	Vision          bool `json:"vision"`
}

type _ProviderCapabilitiesSchema ProviderCapabilitiesSchema

// NewProviderCapabilitiesSchema instantiates a new ProviderCapabilitiesSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderCapabilitiesSchema(audio bool, embeddings bool, imageGeneration bool, listModels bool, moderation bool, pdf bool, reasoning bool, rerank bool, responsesApi bool, streaming bool, vision bool) *ProviderCapabilitiesSchema {
	this := ProviderCapabilitiesSchema{}
	this.Audio = audio
	this.Embeddings = embeddings
	this.ImageGeneration = imageGeneration
	this.ListModels = listModels
	this.Moderation = moderation
	this.Pdf = pdf
	this.Reasoning = reasoning
	this.Rerank = rerank
	this.ResponsesApi = responsesApi
	this.Streaming = streaming
	this.Vision = vision
	return &this
}

// NewProviderCapabilitiesSchemaWithDefaults instantiates a new ProviderCapabilitiesSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderCapabilitiesSchemaWithDefaults() *ProviderCapabilitiesSchema {
	this := ProviderCapabilitiesSchema{}
	return &this
}

// GetAudio returns the Audio field value
func (o *ProviderCapabilitiesSchema) GetAudio() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Audio
}

// GetAudioOk returns a tuple with the Audio field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetAudioOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audio, true
}

// SetAudio sets field value
func (o *ProviderCapabilitiesSchema) SetAudio(v bool) {
	o.Audio = v
}

// GetEmbeddings returns the Embeddings field value
func (o *ProviderCapabilitiesSchema) GetEmbeddings() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Embeddings
}

// GetEmbeddingsOk returns a tuple with the Embeddings field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetEmbeddingsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Embeddings, true
}

// SetEmbeddings sets field value
func (o *ProviderCapabilitiesSchema) SetEmbeddings(v bool) {
	o.Embeddings = v
}

// GetImageGeneration returns the ImageGeneration field value
func (o *ProviderCapabilitiesSchema) GetImageGeneration() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ImageGeneration
}

// GetImageGenerationOk returns a tuple with the ImageGeneration field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetImageGenerationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageGeneration, true
}

// SetImageGeneration sets field value
func (o *ProviderCapabilitiesSchema) SetImageGeneration(v bool) {
	o.ImageGeneration = v
}

// GetListModels returns the ListModels field value
func (o *ProviderCapabilitiesSchema) GetListModels() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ListModels
}

// GetListModelsOk returns a tuple with the ListModels field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetListModelsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListModels, true
}

// SetListModels sets field value
func (o *ProviderCapabilitiesSchema) SetListModels(v bool) {
	o.ListModels = v
}

// GetModeration returns the Moderation field value
func (o *ProviderCapabilitiesSchema) GetModeration() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Moderation
}

// GetModerationOk returns a tuple with the Moderation field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetModerationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Moderation, true
}

// SetModeration sets field value
func (o *ProviderCapabilitiesSchema) SetModeration(v bool) {
	o.Moderation = v
}

// GetPdf returns the Pdf field value
func (o *ProviderCapabilitiesSchema) GetPdf() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Pdf
}

// GetPdfOk returns a tuple with the Pdf field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetPdfOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pdf, true
}

// SetPdf sets field value
func (o *ProviderCapabilitiesSchema) SetPdf(v bool) {
	o.Pdf = v
}

// GetReasoning returns the Reasoning field value
func (o *ProviderCapabilitiesSchema) GetReasoning() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetReasoningOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reasoning, true
}

// SetReasoning sets field value
func (o *ProviderCapabilitiesSchema) SetReasoning(v bool) {
	o.Reasoning = v
}

// GetRerank returns the Rerank field value
func (o *ProviderCapabilitiesSchema) GetRerank() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Rerank
}

// GetRerankOk returns a tuple with the Rerank field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetRerankOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rerank, true
}

// SetRerank sets field value
func (o *ProviderCapabilitiesSchema) SetRerank(v bool) {
	o.Rerank = v
}

// GetResponsesApi returns the ResponsesApi field value
func (o *ProviderCapabilitiesSchema) GetResponsesApi() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ResponsesApi
}

// GetResponsesApiOk returns a tuple with the ResponsesApi field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetResponsesApiOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponsesApi, true
}

// SetResponsesApi sets field value
func (o *ProviderCapabilitiesSchema) SetResponsesApi(v bool) {
	o.ResponsesApi = v
}

// GetStreaming returns the Streaming field value
func (o *ProviderCapabilitiesSchema) GetStreaming() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Streaming
}

// GetStreamingOk returns a tuple with the Streaming field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetStreamingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Streaming, true
}

// SetStreaming sets field value
func (o *ProviderCapabilitiesSchema) SetStreaming(v bool) {
	o.Streaming = v
}

// GetVision returns the Vision field value
func (o *ProviderCapabilitiesSchema) GetVision() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Vision
}

// GetVisionOk returns a tuple with the Vision field value
// and a boolean to check if the value has been set.
func (o *ProviderCapabilitiesSchema) GetVisionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vision, true
}

// SetVision sets field value
func (o *ProviderCapabilitiesSchema) SetVision(v bool) {
	o.Vision = v
}

func (o ProviderCapabilitiesSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderCapabilitiesSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audio"] = o.Audio
	toSerialize["embeddings"] = o.Embeddings
	toSerialize["image_generation"] = o.ImageGeneration
	toSerialize["list_models"] = o.ListModels
	toSerialize["moderation"] = o.Moderation
	toSerialize["pdf"] = o.Pdf
	toSerialize["reasoning"] = o.Reasoning
	toSerialize["rerank"] = o.Rerank
	toSerialize["responses_api"] = o.ResponsesApi
	toSerialize["streaming"] = o.Streaming
	toSerialize["vision"] = o.Vision
	return toSerialize, nil
}

func (o *ProviderCapabilitiesSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audio",
		"embeddings",
		"image_generation",
		"list_models",
		"moderation",
		"pdf",
		"reasoning",
		"rerank",
		"responses_api",
		"streaming",
		"vision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderCapabilitiesSchema := _ProviderCapabilitiesSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderCapabilitiesSchema)

	if err != nil {
		return err
	}

	*o = ProviderCapabilitiesSchema(varProviderCapabilitiesSchema)

	return err
}

type NullableProviderCapabilitiesSchema struct {
	value *ProviderCapabilitiesSchema
	isSet bool
}

func (v NullableProviderCapabilitiesSchema) Get() *ProviderCapabilitiesSchema {
	return v.value
}

func (v *NullableProviderCapabilitiesSchema) Set(val *ProviderCapabilitiesSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderCapabilitiesSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderCapabilitiesSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderCapabilitiesSchema(val *ProviderCapabilitiesSchema) *NullableProviderCapabilitiesSchema {
	return &NullableProviderCapabilitiesSchema{value: val, isSet: true}
}

func (v NullableProviderCapabilitiesSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderCapabilitiesSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
