/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DecisionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecisionRequest{}

// DecisionRequest A decisions request: typed questions to answer about one state.
type DecisionRequest struct {
	// Images for a vision decision model, as data URLs (data:image/...;base64,...). An extension llama-server supports; a provider that does not refuses the request.
	Images []string `json:"images,omitempty"`
	// Decision provider and model, e.g. 'typesafe:jev-latest'
	Model string `json:"model"`
	// Questions, keyed by answer name
	Questions map[string]QuestionsValue `json:"questions"`
	State     State                     `json:"state"`
	// User ID for usage attribution; not sent upstream
	User NullableString `json:"user,omitempty"`
}

type _DecisionRequest DecisionRequest

// NewDecisionRequest instantiates a new DecisionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecisionRequest(model string, questions map[string]QuestionsValue, state State) *DecisionRequest {
	this := DecisionRequest{}
	this.Model = model
	this.Questions = questions
	this.State = state
	return &this
}

// NewDecisionRequestWithDefaults instantiates a new DecisionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecisionRequestWithDefaults() *DecisionRequest {
	this := DecisionRequest{}
	return &this
}

// GetImages returns the Images field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DecisionRequest) GetImages() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DecisionRequest) GetImagesOk() ([]string, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *DecisionRequest) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []string and assigns it to the Images field.
func (o *DecisionRequest) SetImages(v []string) {
	o.Images = v
}

// GetModel returns the Model field value
func (o *DecisionRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *DecisionRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *DecisionRequest) SetModel(v string) {
	o.Model = v
}

// GetQuestions returns the Questions field value
func (o *DecisionRequest) GetQuestions() map[string]QuestionsValue {
	if o == nil {
		var ret map[string]QuestionsValue
		return ret
	}

	return o.Questions
}

// GetQuestionsOk returns a tuple with the Questions field value
// and a boolean to check if the value has been set.
func (o *DecisionRequest) GetQuestionsOk() (map[string]QuestionsValue, bool) {
	if o == nil {
		return map[string]QuestionsValue{}, false
	}
	return o.Questions, true
}

// SetQuestions sets field value
func (o *DecisionRequest) SetQuestions(v map[string]QuestionsValue) {
	o.Questions = v
}

// GetState returns the State field value
func (o *DecisionRequest) GetState() State {
	if o == nil {
		var ret State
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *DecisionRequest) GetStateOk() (*State, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *DecisionRequest) SetState(v State) {
	o.State = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DecisionRequest) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DecisionRequest) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *DecisionRequest) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *DecisionRequest) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *DecisionRequest) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *DecisionRequest) UnsetUser() {
	o.User.Unset()
}

func (o DecisionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecisionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Images != nil {
		toSerialize["images"] = o.Images
	}
	toSerialize["model"] = o.Model
	toSerialize["questions"] = o.Questions
	toSerialize["state"] = o.State
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	return toSerialize, nil
}

func (o *DecisionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model",
		"questions",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecisionRequest := _DecisionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDecisionRequest)

	if err != nil {
		return err
	}

	*o = DecisionRequest(varDecisionRequest)

	return err
}

type NullableDecisionRequest struct {
	value *DecisionRequest
	isSet bool
}

func (v NullableDecisionRequest) Get() *DecisionRequest {
	return v.value
}

func (v *NullableDecisionRequest) Set(val *DecisionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDecisionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDecisionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecisionRequest(val *DecisionRequest) *NullableDecisionRequest {
	return &NullableDecisionRequest{value: val, isSet: true}
}

func (v NullableDecisionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecisionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
