/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeploymentAdminAccessPublic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentAdminAccessPublic{}

// DeploymentAdminAccessPublic Whether the caller may reach the deployment administration surface.  The one endpoint in that surface that answers 200 for everybody, and deliberately: the rest refuse with 404 so they do not confirm they exist, which leaves the dashboard nothing to gate its navigation on but a failed request. This says the same thing a caller could learn by trying, without the try.
type DeploymentAdminAccessPublic struct {
	Granted bool `json:"granted"`
}

type _DeploymentAdminAccessPublic DeploymentAdminAccessPublic

// NewDeploymentAdminAccessPublic instantiates a new DeploymentAdminAccessPublic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentAdminAccessPublic(granted bool) *DeploymentAdminAccessPublic {
	this := DeploymentAdminAccessPublic{}
	this.Granted = granted
	return &this
}

// NewDeploymentAdminAccessPublicWithDefaults instantiates a new DeploymentAdminAccessPublic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentAdminAccessPublicWithDefaults() *DeploymentAdminAccessPublic {
	this := DeploymentAdminAccessPublic{}
	return &this
}

// GetGranted returns the Granted field value
func (o *DeploymentAdminAccessPublic) GetGranted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Granted
}

// GetGrantedOk returns a tuple with the Granted field value
// and a boolean to check if the value has been set.
func (o *DeploymentAdminAccessPublic) GetGrantedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Granted, true
}

// SetGranted sets field value
func (o *DeploymentAdminAccessPublic) SetGranted(v bool) {
	o.Granted = v
}

func (o DeploymentAdminAccessPublic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentAdminAccessPublic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["granted"] = o.Granted
	return toSerialize, nil
}

func (o *DeploymentAdminAccessPublic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"granted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentAdminAccessPublic := _DeploymentAdminAccessPublic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentAdminAccessPublic)

	if err != nil {
		return err
	}

	*o = DeploymentAdminAccessPublic(varDeploymentAdminAccessPublic)

	return err
}

type NullableDeploymentAdminAccessPublic struct {
	value *DeploymentAdminAccessPublic
	isSet bool
}

func (v NullableDeploymentAdminAccessPublic) Get() *DeploymentAdminAccessPublic {
	return v.value
}

func (v *NullableDeploymentAdminAccessPublic) Set(val *DeploymentAdminAccessPublic) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentAdminAccessPublic) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentAdminAccessPublic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentAdminAccessPublic(val *DeploymentAdminAccessPublic) *NullableDeploymentAdminAccessPublic {
	return &NullableDeploymentAdminAccessPublic{value: val, isSet: true}
}

func (v NullableDeploymentAdminAccessPublic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentAdminAccessPublic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
