/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CCKChoiceDeltaFunctionCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CCKChoiceDeltaFunctionCall{}

// CCKChoiceDeltaFunctionCall Deprecated and replaced by `tool_calls`.  The name and arguments of a function that should be called, as generated by the model.
type CCKChoiceDeltaFunctionCall struct {
	// Filter models by provider name
	Arguments NullableString `json:"arguments,omitempty"`
	// Filter models by provider name
	Name                 NullableString `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CCKChoiceDeltaFunctionCall CCKChoiceDeltaFunctionCall

// NewCCKChoiceDeltaFunctionCall instantiates a new CCKChoiceDeltaFunctionCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCCKChoiceDeltaFunctionCall() *CCKChoiceDeltaFunctionCall {
	this := CCKChoiceDeltaFunctionCall{}
	return &this
}

// NewCCKChoiceDeltaFunctionCallWithDefaults instantiates a new CCKChoiceDeltaFunctionCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCCKChoiceDeltaFunctionCallWithDefaults() *CCKChoiceDeltaFunctionCall {
	this := CCKChoiceDeltaFunctionCall{}
	return &this
}

// GetArguments returns the Arguments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CCKChoiceDeltaFunctionCall) GetArguments() string {
	if o == nil || IsNil(o.Arguments.Get()) {
		var ret string
		return ret
	}
	return *o.Arguments.Get()
}

// GetArgumentsOk returns a tuple with the Arguments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CCKChoiceDeltaFunctionCall) GetArgumentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Arguments.Get(), o.Arguments.IsSet()
}

// HasArguments returns a boolean if a field has been set.
func (o *CCKChoiceDeltaFunctionCall) HasArguments() bool {
	if o != nil && o.Arguments.IsSet() {
		return true
	}

	return false
}

// SetArguments gets a reference to the given NullableString and assigns it to the Arguments field.
func (o *CCKChoiceDeltaFunctionCall) SetArguments(v string) {
	o.Arguments.Set(&v)
}

// SetArgumentsNil sets the value for Arguments to be an explicit nil
func (o *CCKChoiceDeltaFunctionCall) SetArgumentsNil() {
	o.Arguments.Set(nil)
}

// UnsetArguments ensures that no value is present for Arguments, not even an explicit nil
func (o *CCKChoiceDeltaFunctionCall) UnsetArguments() {
	o.Arguments.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CCKChoiceDeltaFunctionCall) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CCKChoiceDeltaFunctionCall) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CCKChoiceDeltaFunctionCall) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CCKChoiceDeltaFunctionCall) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *CCKChoiceDeltaFunctionCall) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CCKChoiceDeltaFunctionCall) UnsetName() {
	o.Name.Unset()
}

func (o CCKChoiceDeltaFunctionCall) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CCKChoiceDeltaFunctionCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Arguments.IsSet() {
		toSerialize["arguments"] = o.Arguments.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CCKChoiceDeltaFunctionCall) UnmarshalJSON(data []byte) (err error) {
	varCCKChoiceDeltaFunctionCall := _CCKChoiceDeltaFunctionCall{}

	err = json.Unmarshal(data, &varCCKChoiceDeltaFunctionCall)

	if err != nil {
		return err
	}

	*o = CCKChoiceDeltaFunctionCall(varCCKChoiceDeltaFunctionCall)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "arguments")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCCKChoiceDeltaFunctionCall struct {
	value *CCKChoiceDeltaFunctionCall
	isSet bool
}

func (v NullableCCKChoiceDeltaFunctionCall) Get() *CCKChoiceDeltaFunctionCall {
	return v.value
}

func (v *NullableCCKChoiceDeltaFunctionCall) Set(val *CCKChoiceDeltaFunctionCall) {
	v.value = val
	v.isSet = true
}

func (v NullableCCKChoiceDeltaFunctionCall) IsSet() bool {
	return v.isSet
}

func (v *NullableCCKChoiceDeltaFunctionCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCCKChoiceDeltaFunctionCall(val *CCKChoiceDeltaFunctionCall) *NullableCCKChoiceDeltaFunctionCall {
	return &NullableCCKChoiceDeltaFunctionCall{value: val, isSet: true}
}

func (v NullableCCKChoiceDeltaFunctionCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCCKChoiceDeltaFunctionCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
