/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DeploymentUserUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentUserUpdateRequest{}

// DeploymentUserUpdateRequest The two flags the operator surface may flip, each optional.  Omitting a field leaves it alone, so deactivating an account and changing what it may administer stay separate decisions even though one endpoint carries both. A body that sets neither is refused rather than treated as a no-op: it is a request that meant something and lost it.
type DeploymentUserUpdateRequest struct {
	IsActive    NullableBool `json:"is_active,omitempty"`
	IsSuperuser NullableBool `json:"is_superuser,omitempty"`
}

// NewDeploymentUserUpdateRequest instantiates a new DeploymentUserUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentUserUpdateRequest() *DeploymentUserUpdateRequest {
	this := DeploymentUserUpdateRequest{}
	return &this
}

// NewDeploymentUserUpdateRequestWithDefaults instantiates a new DeploymentUserUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentUserUpdateRequestWithDefaults() *DeploymentUserUpdateRequest {
	this := DeploymentUserUpdateRequest{}
	return &this
}

// GetIsActive returns the IsActive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentUserUpdateRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive.Get()) {
		var ret bool
		return ret
	}
	return *o.IsActive.Get()
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentUserUpdateRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsActive.Get(), o.IsActive.IsSet()
}

// HasIsActive returns a boolean if a field has been set.
func (o *DeploymentUserUpdateRequest) HasIsActive() bool {
	if o != nil && o.IsActive.IsSet() {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given NullableBool and assigns it to the IsActive field.
func (o *DeploymentUserUpdateRequest) SetIsActive(v bool) {
	o.IsActive.Set(&v)
}

// SetIsActiveNil sets the value for IsActive to be an explicit nil
func (o *DeploymentUserUpdateRequest) SetIsActiveNil() {
	o.IsActive.Set(nil)
}

// UnsetIsActive ensures that no value is present for IsActive, not even an explicit nil
func (o *DeploymentUserUpdateRequest) UnsetIsActive() {
	o.IsActive.Unset()
}

// GetIsSuperuser returns the IsSuperuser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentUserUpdateRequest) GetIsSuperuser() bool {
	if o == nil || IsNil(o.IsSuperuser.Get()) {
		var ret bool
		return ret
	}
	return *o.IsSuperuser.Get()
}

// GetIsSuperuserOk returns a tuple with the IsSuperuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentUserUpdateRequest) GetIsSuperuserOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsSuperuser.Get(), o.IsSuperuser.IsSet()
}

// HasIsSuperuser returns a boolean if a field has been set.
func (o *DeploymentUserUpdateRequest) HasIsSuperuser() bool {
	if o != nil && o.IsSuperuser.IsSet() {
		return true
	}

	return false
}

// SetIsSuperuser gets a reference to the given NullableBool and assigns it to the IsSuperuser field.
func (o *DeploymentUserUpdateRequest) SetIsSuperuser(v bool) {
	o.IsSuperuser.Set(&v)
}

// SetIsSuperuserNil sets the value for IsSuperuser to be an explicit nil
func (o *DeploymentUserUpdateRequest) SetIsSuperuserNil() {
	o.IsSuperuser.Set(nil)
}

// UnsetIsSuperuser ensures that no value is present for IsSuperuser, not even an explicit nil
func (o *DeploymentUserUpdateRequest) UnsetIsSuperuser() {
	o.IsSuperuser.Unset()
}

func (o DeploymentUserUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentUserUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IsActive.IsSet() {
		toSerialize["is_active"] = o.IsActive.Get()
	}
	if o.IsSuperuser.IsSet() {
		toSerialize["is_superuser"] = o.IsSuperuser.Get()
	}
	return toSerialize, nil
}

type NullableDeploymentUserUpdateRequest struct {
	value *DeploymentUserUpdateRequest
	isSet bool
}

func (v NullableDeploymentUserUpdateRequest) Get() *DeploymentUserUpdateRequest {
	return v.value
}

func (v *NullableDeploymentUserUpdateRequest) Set(val *DeploymentUserUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentUserUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentUserUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentUserUpdateRequest(val *DeploymentUserUpdateRequest) *NullableDeploymentUserUpdateRequest {
	return &NullableDeploymentUserUpdateRequest{value: val, isSet: true}
}

func (v NullableDeploymentUserUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentUserUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
