/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the UsageSetPriceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageSetPriceRequest{}

// UsageSetPriceRequest Selection of imported usage rows plus the manual per-1M rates to price them at.  “input“ and “output“ are required (every row is charged for them); the cache rates are optional and, when omitted, those tokens fold into the fresh-input charge exactly as an unpriced cache rate does in normal metered pricing.
type UsageSetPriceRequest struct {
	ApiKeyId                  NullableApiKeyId `json:"api_key_id,omitempty"`
	ByFilter                  *bool            `json:"by_filter,omitempty"`
	CacheReadPricePerMillion  NullableFloat32  `json:"cache_read_price_per_million,omitempty"`
	CacheWritePricePerMillion NullableFloat32  `json:"cache_write_price_per_million,omitempty"`
	EndDate                   NullableTime     `json:"end_date,omitempty"`
	Endpoint                  NullableString   `json:"endpoint,omitempty"`
	Ids                       []string         `json:"ids,omitempty"`
	InputPricePerMillion      float32          `json:"input_price_per_million"`
	Model                     NullableModel    `json:"model,omitempty"`
	OutputPricePerMillion     float32          `json:"output_price_per_million"`
	Priced                    NullableBool     `json:"priced,omitempty"`
	Provider                  NullableString   `json:"provider,omitempty"`
	Source                    NullableString   `json:"source,omitempty"`
	SourceLabel               NullableString   `json:"source_label,omitempty"`
	StartDate                 NullableTime     `json:"start_date,omitempty"`
	Status                    NullableString   `json:"status,omitempty"`
	Tool                      NullableString   `json:"tool,omitempty"`
	UserId                    NullableUserId   `json:"user_id,omitempty"`
}

type _UsageSetPriceRequest UsageSetPriceRequest

// NewUsageSetPriceRequest instantiates a new UsageSetPriceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageSetPriceRequest(inputPricePerMillion float32, outputPricePerMillion float32) *UsageSetPriceRequest {
	this := UsageSetPriceRequest{}
	var byFilter bool = false
	this.ByFilter = &byFilter
	this.InputPricePerMillion = inputPricePerMillion
	this.OutputPricePerMillion = outputPricePerMillion
	return &this
}

// NewUsageSetPriceRequestWithDefaults instantiates a new UsageSetPriceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageSetPriceRequestWithDefaults() *UsageSetPriceRequest {
	this := UsageSetPriceRequest{}
	var byFilter bool = false
	this.ByFilter = &byFilter
	return &this
}

// GetApiKeyId returns the ApiKeyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetApiKeyId() ApiKeyId {
	if o == nil || IsNil(o.ApiKeyId.Get()) {
		var ret ApiKeyId
		return ret
	}
	return *o.ApiKeyId.Get()
}

// GetApiKeyIdOk returns a tuple with the ApiKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetApiKeyIdOk() (*ApiKeyId, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKeyId.Get(), o.ApiKeyId.IsSet()
}

// HasApiKeyId returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasApiKeyId() bool {
	if o != nil && o.ApiKeyId.IsSet() {
		return true
	}

	return false
}

// SetApiKeyId gets a reference to the given NullableApiKeyId and assigns it to the ApiKeyId field.
func (o *UsageSetPriceRequest) SetApiKeyId(v ApiKeyId) {
	o.ApiKeyId.Set(&v)
}

// SetApiKeyIdNil sets the value for ApiKeyId to be an explicit nil
func (o *UsageSetPriceRequest) SetApiKeyIdNil() {
	o.ApiKeyId.Set(nil)
}

// UnsetApiKeyId ensures that no value is present for ApiKeyId, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetApiKeyId() {
	o.ApiKeyId.Unset()
}

// GetByFilter returns the ByFilter field value if set, zero value otherwise.
func (o *UsageSetPriceRequest) GetByFilter() bool {
	if o == nil || IsNil(o.ByFilter) {
		var ret bool
		return ret
	}
	return *o.ByFilter
}

// GetByFilterOk returns a tuple with the ByFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageSetPriceRequest) GetByFilterOk() (*bool, bool) {
	if o == nil || IsNil(o.ByFilter) {
		return nil, false
	}
	return o.ByFilter, true
}

// HasByFilter returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasByFilter() bool {
	if o != nil && !IsNil(o.ByFilter) {
		return true
	}

	return false
}

// SetByFilter gets a reference to the given bool and assigns it to the ByFilter field.
func (o *UsageSetPriceRequest) SetByFilter(v bool) {
	o.ByFilter = &v
}

// GetCacheReadPricePerMillion returns the CacheReadPricePerMillion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetCacheReadPricePerMillion() float32 {
	if o == nil || IsNil(o.CacheReadPricePerMillion.Get()) {
		var ret float32
		return ret
	}
	return *o.CacheReadPricePerMillion.Get()
}

// GetCacheReadPricePerMillionOk returns a tuple with the CacheReadPricePerMillion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetCacheReadPricePerMillionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CacheReadPricePerMillion.Get(), o.CacheReadPricePerMillion.IsSet()
}

// HasCacheReadPricePerMillion returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasCacheReadPricePerMillion() bool {
	if o != nil && o.CacheReadPricePerMillion.IsSet() {
		return true
	}

	return false
}

// SetCacheReadPricePerMillion gets a reference to the given NullableFloat32 and assigns it to the CacheReadPricePerMillion field.
func (o *UsageSetPriceRequest) SetCacheReadPricePerMillion(v float32) {
	o.CacheReadPricePerMillion.Set(&v)
}

// SetCacheReadPricePerMillionNil sets the value for CacheReadPricePerMillion to be an explicit nil
func (o *UsageSetPriceRequest) SetCacheReadPricePerMillionNil() {
	o.CacheReadPricePerMillion.Set(nil)
}

// UnsetCacheReadPricePerMillion ensures that no value is present for CacheReadPricePerMillion, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetCacheReadPricePerMillion() {
	o.CacheReadPricePerMillion.Unset()
}

// GetCacheWritePricePerMillion returns the CacheWritePricePerMillion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetCacheWritePricePerMillion() float32 {
	if o == nil || IsNil(o.CacheWritePricePerMillion.Get()) {
		var ret float32
		return ret
	}
	return *o.CacheWritePricePerMillion.Get()
}

// GetCacheWritePricePerMillionOk returns a tuple with the CacheWritePricePerMillion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetCacheWritePricePerMillionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CacheWritePricePerMillion.Get(), o.CacheWritePricePerMillion.IsSet()
}

// HasCacheWritePricePerMillion returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasCacheWritePricePerMillion() bool {
	if o != nil && o.CacheWritePricePerMillion.IsSet() {
		return true
	}

	return false
}

// SetCacheWritePricePerMillion gets a reference to the given NullableFloat32 and assigns it to the CacheWritePricePerMillion field.
func (o *UsageSetPriceRequest) SetCacheWritePricePerMillion(v float32) {
	o.CacheWritePricePerMillion.Set(&v)
}

// SetCacheWritePricePerMillionNil sets the value for CacheWritePricePerMillion to be an explicit nil
func (o *UsageSetPriceRequest) SetCacheWritePricePerMillionNil() {
	o.CacheWritePricePerMillion.Set(nil)
}

// UnsetCacheWritePricePerMillion ensures that no value is present for CacheWritePricePerMillion, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetCacheWritePricePerMillion() {
	o.CacheWritePricePerMillion.Unset()
}

// GetEndDate returns the EndDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// HasEndDate returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasEndDate() bool {
	if o != nil && o.EndDate.IsSet() {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given NullableTime and assigns it to the EndDate field.
func (o *UsageSetPriceRequest) SetEndDate(v time.Time) {
	o.EndDate.Set(&v)
}

// SetEndDateNil sets the value for EndDate to be an explicit nil
func (o *UsageSetPriceRequest) SetEndDateNil() {
	o.EndDate.Set(nil)
}

// UnsetEndDate ensures that no value is present for EndDate, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetEndDate() {
	o.EndDate.Unset()
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint.Get()) {
		var ret string
		return ret
	}
	return *o.Endpoint.Get()
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoint.Get(), o.Endpoint.IsSet()
}

// HasEndpoint returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasEndpoint() bool {
	if o != nil && o.Endpoint.IsSet() {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given NullableString and assigns it to the Endpoint field.
func (o *UsageSetPriceRequest) SetEndpoint(v string) {
	o.Endpoint.Set(&v)
}

// SetEndpointNil sets the value for Endpoint to be an explicit nil
func (o *UsageSetPriceRequest) SetEndpointNil() {
	o.Endpoint.Set(nil)
}

// UnsetEndpoint ensures that no value is present for Endpoint, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetEndpoint() {
	o.Endpoint.Unset()
}

// GetIds returns the Ids field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *UsageSetPriceRequest) SetIds(v []string) {
	o.Ids = v
}

// GetInputPricePerMillion returns the InputPricePerMillion field value
func (o *UsageSetPriceRequest) GetInputPricePerMillion() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.InputPricePerMillion
}

// GetInputPricePerMillionOk returns a tuple with the InputPricePerMillion field value
// and a boolean to check if the value has been set.
func (o *UsageSetPriceRequest) GetInputPricePerMillionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputPricePerMillion, true
}

// SetInputPricePerMillion sets field value
func (o *UsageSetPriceRequest) SetInputPricePerMillion(v float32) {
	o.InputPricePerMillion = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetModel() Model {
	if o == nil || IsNil(o.Model.Get()) {
		var ret Model
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetModelOk() (*Model, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableModel and assigns it to the Model field.
func (o *UsageSetPriceRequest) SetModel(v Model) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *UsageSetPriceRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetModel() {
	o.Model.Unset()
}

// GetOutputPricePerMillion returns the OutputPricePerMillion field value
func (o *UsageSetPriceRequest) GetOutputPricePerMillion() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OutputPricePerMillion
}

// GetOutputPricePerMillionOk returns a tuple with the OutputPricePerMillion field value
// and a boolean to check if the value has been set.
func (o *UsageSetPriceRequest) GetOutputPricePerMillionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutputPricePerMillion, true
}

// SetOutputPricePerMillion sets field value
func (o *UsageSetPriceRequest) SetOutputPricePerMillion(v float32) {
	o.OutputPricePerMillion = v
}

// GetPriced returns the Priced field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetPriced() bool {
	if o == nil || IsNil(o.Priced.Get()) {
		var ret bool
		return ret
	}
	return *o.Priced.Get()
}

// GetPricedOk returns a tuple with the Priced field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetPricedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priced.Get(), o.Priced.IsSet()
}

// HasPriced returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasPriced() bool {
	if o != nil && o.Priced.IsSet() {
		return true
	}

	return false
}

// SetPriced gets a reference to the given NullableBool and assigns it to the Priced field.
func (o *UsageSetPriceRequest) SetPriced(v bool) {
	o.Priced.Set(&v)
}

// SetPricedNil sets the value for Priced to be an explicit nil
func (o *UsageSetPriceRequest) SetPricedNil() {
	o.Priced.Set(nil)
}

// UnsetPriced ensures that no value is present for Priced, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetPriced() {
	o.Priced.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *UsageSetPriceRequest) SetProvider(v string) {
	o.Provider.Set(&v)
}

// SetProviderNil sets the value for Provider to be an explicit nil
func (o *UsageSetPriceRequest) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetProvider() {
	o.Provider.Unset()
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetSource() string {
	if o == nil || IsNil(o.Source.Get()) {
		var ret string
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableString and assigns it to the Source field.
func (o *UsageSetPriceRequest) SetSource(v string) {
	o.Source.Set(&v)
}

// SetSourceNil sets the value for Source to be an explicit nil
func (o *UsageSetPriceRequest) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetSource() {
	o.Source.Unset()
}

// GetSourceLabel returns the SourceLabel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetSourceLabel() string {
	if o == nil || IsNil(o.SourceLabel.Get()) {
		var ret string
		return ret
	}
	return *o.SourceLabel.Get()
}

// GetSourceLabelOk returns a tuple with the SourceLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetSourceLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceLabel.Get(), o.SourceLabel.IsSet()
}

// HasSourceLabel returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasSourceLabel() bool {
	if o != nil && o.SourceLabel.IsSet() {
		return true
	}

	return false
}

// SetSourceLabel gets a reference to the given NullableString and assigns it to the SourceLabel field.
func (o *UsageSetPriceRequest) SetSourceLabel(v string) {
	o.SourceLabel.Set(&v)
}

// SetSourceLabelNil sets the value for SourceLabel to be an explicit nil
func (o *UsageSetPriceRequest) SetSourceLabelNil() {
	o.SourceLabel.Set(nil)
}

// UnsetSourceLabel ensures that no value is present for SourceLabel, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetSourceLabel() {
	o.SourceLabel.Unset()
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableTime and assigns it to the StartDate field.
func (o *UsageSetPriceRequest) SetStartDate(v time.Time) {
	o.StartDate.Set(&v)
}

// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *UsageSetPriceRequest) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *UsageSetPriceRequest) SetStatus(v string) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *UsageSetPriceRequest) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetStatus() {
	o.Status.Unset()
}

// GetTool returns the Tool field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetTool() string {
	if o == nil || IsNil(o.Tool.Get()) {
		var ret string
		return ret
	}
	return *o.Tool.Get()
}

// GetToolOk returns a tuple with the Tool field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tool.Get(), o.Tool.IsSet()
}

// HasTool returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasTool() bool {
	if o != nil && o.Tool.IsSet() {
		return true
	}

	return false
}

// SetTool gets a reference to the given NullableString and assigns it to the Tool field.
func (o *UsageSetPriceRequest) SetTool(v string) {
	o.Tool.Set(&v)
}

// SetToolNil sets the value for Tool to be an explicit nil
func (o *UsageSetPriceRequest) SetToolNil() {
	o.Tool.Set(nil)
}

// UnsetTool ensures that no value is present for Tool, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetTool() {
	o.Tool.Unset()
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageSetPriceRequest) GetUserId() UserId {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret UserId
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageSetPriceRequest) GetUserIdOk() (*UserId, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *UsageSetPriceRequest) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableUserId and assigns it to the UserId field.
func (o *UsageSetPriceRequest) SetUserId(v UserId) {
	o.UserId.Set(&v)
}

// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *UsageSetPriceRequest) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *UsageSetPriceRequest) UnsetUserId() {
	o.UserId.Unset()
}

func (o UsageSetPriceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageSetPriceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKeyId.IsSet() {
		toSerialize["api_key_id"] = o.ApiKeyId.Get()
	}
	if !IsNil(o.ByFilter) {
		toSerialize["by_filter"] = o.ByFilter
	}
	if o.CacheReadPricePerMillion.IsSet() {
		toSerialize["cache_read_price_per_million"] = o.CacheReadPricePerMillion.Get()
	}
	if o.CacheWritePricePerMillion.IsSet() {
		toSerialize["cache_write_price_per_million"] = o.CacheWritePricePerMillion.Get()
	}
	if o.EndDate.IsSet() {
		toSerialize["end_date"] = o.EndDate.Get()
	}
	if o.Endpoint.IsSet() {
		toSerialize["endpoint"] = o.Endpoint.Get()
	}
	if o.Ids != nil {
		toSerialize["ids"] = o.Ids
	}
	toSerialize["input_price_per_million"] = o.InputPricePerMillion
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	toSerialize["output_price_per_million"] = o.OutputPricePerMillion
	if o.Priced.IsSet() {
		toSerialize["priced"] = o.Priced.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.SourceLabel.IsSet() {
		toSerialize["source_label"] = o.SourceLabel.Get()
	}
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Tool.IsSet() {
		toSerialize["tool"] = o.Tool.Get()
	}
	if o.UserId.IsSet() {
		toSerialize["user_id"] = o.UserId.Get()
	}
	return toSerialize, nil
}

func (o *UsageSetPriceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input_price_per_million",
		"output_price_per_million",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageSetPriceRequest := _UsageSetPriceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageSetPriceRequest)

	if err != nil {
		return err
	}

	*o = UsageSetPriceRequest(varUsageSetPriceRequest)

	return err
}

type NullableUsageSetPriceRequest struct {
	value *UsageSetPriceRequest
	isSet bool
}

func (v NullableUsageSetPriceRequest) Get() *UsageSetPriceRequest {
	return v.value
}

func (v *NullableUsageSetPriceRequest) Set(val *UsageSetPriceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageSetPriceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageSetPriceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageSetPriceRequest(val *UsageSetPriceRequest) *NullableUsageSetPriceRequest {
	return &NullableUsageSetPriceRequest{value: val, isSet: true}
}

func (v NullableUsageSetPriceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageSetPriceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
