/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserResponse{}

// UserResponse Response model for user information.
type UserResponse struct {
	Alias             NullableString         `json:"alias"`
	AllowedModels     []string               `json:"allowed_models"`
	Blocked           bool                   `json:"blocked"`
	BudgetId          NullableString         `json:"budget_id"`
	BudgetStartedAt   NullableString         `json:"budget_started_at"`
	CreatedAt         string                 `json:"created_at"`
	CurrentRequests   int32                  `json:"current_requests"`
	CurrentTokens     int32                  `json:"current_tokens"`
	ExternalId        NullableString         `json:"external_id,omitempty"`
	Metadata          map[string]interface{} `json:"metadata"`
	NextBudgetResetAt NullableString         `json:"next_budget_reset_at"`
	ParentUserId      NullableString         `json:"parent_user_id,omitempty"`
	Reserved          float32                `json:"reserved"`
	ReservedRequests  int32                  `json:"reserved_requests"`
	ReservedTokens    int32                  `json:"reserved_tokens"`
	Spend             float32                `json:"spend"`
	UpdatedAt         string                 `json:"updated_at"`
	UserId            string                 `json:"user_id"`
}

type _UserResponse UserResponse

// NewUserResponse instantiates a new UserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserResponse(alias NullableString, allowedModels []string, blocked bool, budgetId NullableString, budgetStartedAt NullableString, createdAt string, currentRequests int32, currentTokens int32, metadata map[string]interface{}, nextBudgetResetAt NullableString, reserved float32, reservedRequests int32, reservedTokens int32, spend float32, updatedAt string, userId string) *UserResponse {
	this := UserResponse{}
	this.Alias = alias
	this.AllowedModels = allowedModels
	this.Blocked = blocked
	this.BudgetId = budgetId
	this.BudgetStartedAt = budgetStartedAt
	this.CreatedAt = createdAt
	this.CurrentRequests = currentRequests
	this.CurrentTokens = currentTokens
	this.Metadata = metadata
	this.NextBudgetResetAt = nextBudgetResetAt
	this.Reserved = reserved
	this.ReservedRequests = reservedRequests
	this.ReservedTokens = reservedTokens
	this.Spend = spend
	this.UpdatedAt = updatedAt
	this.UserId = userId
	return &this
}

// NewUserResponseWithDefaults instantiates a new UserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserResponseWithDefaults() *UserResponse {
	this := UserResponse{}
	return &this
}

// GetAlias returns the Alias field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserResponse) GetAlias() string {
	if o == nil || o.Alias.Get() == nil {
		var ret string
		return ret
	}

	return *o.Alias.Get()
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alias.Get(), o.Alias.IsSet()
}

// SetAlias sets field value
func (o *UserResponse) SetAlias(v string) {
	o.Alias.Set(&v)
}

// GetAllowedModels returns the AllowedModels field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *UserResponse) GetAllowedModels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedModels
}

// GetAllowedModelsOk returns a tuple with the AllowedModels field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetAllowedModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedModels) {
		return nil, false
	}
	return o.AllowedModels, true
}

// SetAllowedModels sets field value
func (o *UserResponse) SetAllowedModels(v []string) {
	o.AllowedModels = v
}

// GetBlocked returns the Blocked field value
func (o *UserResponse) GetBlocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetBlockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Blocked, true
}

// SetBlocked sets field value
func (o *UserResponse) SetBlocked(v bool) {
	o.Blocked = v
}

// GetBudgetId returns the BudgetId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserResponse) GetBudgetId() string {
	if o == nil || o.BudgetId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BudgetId.Get()
}

// GetBudgetIdOk returns a tuple with the BudgetId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetBudgetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BudgetId.Get(), o.BudgetId.IsSet()
}

// SetBudgetId sets field value
func (o *UserResponse) SetBudgetId(v string) {
	o.BudgetId.Set(&v)
}

// GetBudgetStartedAt returns the BudgetStartedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserResponse) GetBudgetStartedAt() string {
	if o == nil || o.BudgetStartedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.BudgetStartedAt.Get()
}

// GetBudgetStartedAtOk returns a tuple with the BudgetStartedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetBudgetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BudgetStartedAt.Get(), o.BudgetStartedAt.IsSet()
}

// SetBudgetStartedAt sets field value
func (o *UserResponse) SetBudgetStartedAt(v string) {
	o.BudgetStartedAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCurrentRequests returns the CurrentRequests field value
func (o *UserResponse) GetCurrentRequests() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentRequests
}

// GetCurrentRequestsOk returns a tuple with the CurrentRequests field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetCurrentRequestsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentRequests, true
}

// SetCurrentRequests sets field value
func (o *UserResponse) SetCurrentRequests(v int32) {
	o.CurrentRequests = v
}

// GetCurrentTokens returns the CurrentTokens field value
func (o *UserResponse) GetCurrentTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentTokens
}

// GetCurrentTokensOk returns a tuple with the CurrentTokens field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetCurrentTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentTokens, true
}

// SetCurrentTokens sets field value
func (o *UserResponse) SetCurrentTokens(v int32) {
	o.CurrentTokens = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserResponse) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *UserResponse) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *UserResponse) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *UserResponse) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *UserResponse) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetMetadata returns the Metadata field value
func (o *UserResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *UserResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetNextBudgetResetAt returns the NextBudgetResetAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserResponse) GetNextBudgetResetAt() string {
	if o == nil || o.NextBudgetResetAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextBudgetResetAt.Get()
}

// GetNextBudgetResetAtOk returns a tuple with the NextBudgetResetAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetNextBudgetResetAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextBudgetResetAt.Get(), o.NextBudgetResetAt.IsSet()
}

// SetNextBudgetResetAt sets field value
func (o *UserResponse) SetNextBudgetResetAt(v string) {
	o.NextBudgetResetAt.Set(&v)
}

// GetParentUserId returns the ParentUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserResponse) GetParentUserId() string {
	if o == nil || IsNil(o.ParentUserId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentUserId.Get()
}

// GetParentUserIdOk returns a tuple with the ParentUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserResponse) GetParentUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentUserId.Get(), o.ParentUserId.IsSet()
}

// HasParentUserId returns a boolean if a field has been set.
func (o *UserResponse) HasParentUserId() bool {
	if o != nil && o.ParentUserId.IsSet() {
		return true
	}

	return false
}

// SetParentUserId gets a reference to the given NullableString and assigns it to the ParentUserId field.
func (o *UserResponse) SetParentUserId(v string) {
	o.ParentUserId.Set(&v)
}

// SetParentUserIdNil sets the value for ParentUserId to be an explicit nil
func (o *UserResponse) SetParentUserIdNil() {
	o.ParentUserId.Set(nil)
}

// UnsetParentUserId ensures that no value is present for ParentUserId, not even an explicit nil
func (o *UserResponse) UnsetParentUserId() {
	o.ParentUserId.Unset()
}

// GetReserved returns the Reserved field value
func (o *UserResponse) GetReserved() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Reserved
}

// GetReservedOk returns a tuple with the Reserved field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetReservedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reserved, true
}

// SetReserved sets field value
func (o *UserResponse) SetReserved(v float32) {
	o.Reserved = v
}

// GetReservedRequests returns the ReservedRequests field value
func (o *UserResponse) GetReservedRequests() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedRequests
}

// GetReservedRequestsOk returns a tuple with the ReservedRequests field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetReservedRequestsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedRequests, true
}

// SetReservedRequests sets field value
func (o *UserResponse) SetReservedRequests(v int32) {
	o.ReservedRequests = v
}

// GetReservedTokens returns the ReservedTokens field value
func (o *UserResponse) GetReservedTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedTokens
}

// GetReservedTokensOk returns a tuple with the ReservedTokens field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetReservedTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedTokens, true
}

// SetReservedTokens sets field value
func (o *UserResponse) SetReservedTokens(v int32) {
	o.ReservedTokens = v
}

// GetSpend returns the Spend field value
func (o *UserResponse) GetSpend() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Spend
}

// GetSpendOk returns a tuple with the Spend field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetSpendOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spend, true
}

// SetSpend sets field value
func (o *UserResponse) SetSpend(v float32) {
	o.Spend = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetUserId returns the UserId field value
func (o *UserResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserResponse) SetUserId(v string) {
	o.UserId = v
}

func (o UserResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alias"] = o.Alias.Get()
	if o.AllowedModels != nil {
		toSerialize["allowed_models"] = o.AllowedModels
	}
	toSerialize["blocked"] = o.Blocked
	toSerialize["budget_id"] = o.BudgetId.Get()
	toSerialize["budget_started_at"] = o.BudgetStartedAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["current_requests"] = o.CurrentRequests
	toSerialize["current_tokens"] = o.CurrentTokens
	if o.ExternalId.IsSet() {
		toSerialize["external_id"] = o.ExternalId.Get()
	}
	toSerialize["metadata"] = o.Metadata
	toSerialize["next_budget_reset_at"] = o.NextBudgetResetAt.Get()
	if o.ParentUserId.IsSet() {
		toSerialize["parent_user_id"] = o.ParentUserId.Get()
	}
	toSerialize["reserved"] = o.Reserved
	toSerialize["reserved_requests"] = o.ReservedRequests
	toSerialize["reserved_tokens"] = o.ReservedTokens
	toSerialize["spend"] = o.Spend
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *UserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alias",
		"allowed_models",
		"blocked",
		"budget_id",
		"budget_started_at",
		"created_at",
		"current_requests",
		"current_tokens",
		"metadata",
		"next_budget_reset_at",
		"reserved",
		"reserved_requests",
		"reserved_tokens",
		"spend",
		"updated_at",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserResponse := _UserResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserResponse)

	if err != nil {
		return err
	}

	*o = UserResponse(varUserResponse)

	return err
}

type NullableUserResponse struct {
	value *UserResponse
	isSet bool
}

func (v NullableUserResponse) Get() *UserResponse {
	return v.value
}

func (v *NullableUserResponse) Set(val *UserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserResponse(val *UserResponse) *NullableUserResponse {
	return &NullableUserResponse{value: val, isSet: true}
}

func (v NullableUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
