/*
otari-gateway

A clean FastAPI gateway for otari with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RerankRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RerankRequest{}

// RerankRequest Rerank request.
type RerankRequest struct {
	// List of document strings to rerank
	Documents []string `json:"documents"`
	// Per-document truncation limit
	MaxTokensPerDoc NullableInt32 `json:"max_tokens_per_doc,omitempty"`
	// Provider-prefixed model ID, e.g. 'cohere:rerank-v3.5'
	Model string `json:"model"`
	// The search query to rerank documents against
	Query string `json:"query"`
	// Maximum number of results to return
	TopN NullableInt32 `json:"top_n,omitempty"`
	// User ID for usage attribution
	User NullableString `json:"user,omitempty"`
}

type _RerankRequest RerankRequest

// NewRerankRequest instantiates a new RerankRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRerankRequest(documents []string, model string, query string) *RerankRequest {
	this := RerankRequest{}
	this.Documents = documents
	this.Model = model
	this.Query = query
	return &this
}

// NewRerankRequestWithDefaults instantiates a new RerankRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRerankRequestWithDefaults() *RerankRequest {
	this := RerankRequest{}
	return &this
}

// GetDocuments returns the Documents field value
func (o *RerankRequest) GetDocuments() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *RerankRequest) GetDocumentsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *RerankRequest) SetDocuments(v []string) {
	o.Documents = v
}

// GetMaxTokensPerDoc returns the MaxTokensPerDoc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RerankRequest) GetMaxTokensPerDoc() int32 {
	if o == nil || IsNil(o.MaxTokensPerDoc.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTokensPerDoc.Get()
}

// GetMaxTokensPerDocOk returns a tuple with the MaxTokensPerDoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RerankRequest) GetMaxTokensPerDocOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTokensPerDoc.Get(), o.MaxTokensPerDoc.IsSet()
}

// HasMaxTokensPerDoc returns a boolean if a field has been set.
func (o *RerankRequest) HasMaxTokensPerDoc() bool {
	if o != nil && o.MaxTokensPerDoc.IsSet() {
		return true
	}

	return false
}

// SetMaxTokensPerDoc gets a reference to the given NullableInt32 and assigns it to the MaxTokensPerDoc field.
func (o *RerankRequest) SetMaxTokensPerDoc(v int32) {
	o.MaxTokensPerDoc.Set(&v)
}

// SetMaxTokensPerDocNil sets the value for MaxTokensPerDoc to be an explicit nil
func (o *RerankRequest) SetMaxTokensPerDocNil() {
	o.MaxTokensPerDoc.Set(nil)
}

// UnsetMaxTokensPerDoc ensures that no value is present for MaxTokensPerDoc, not even an explicit nil
func (o *RerankRequest) UnsetMaxTokensPerDoc() {
	o.MaxTokensPerDoc.Unset()
}

// GetModel returns the Model field value
func (o *RerankRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *RerankRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *RerankRequest) SetModel(v string) {
	o.Model = v
}

// GetQuery returns the Query field value
func (o *RerankRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *RerankRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *RerankRequest) SetQuery(v string) {
	o.Query = v
}

// GetTopN returns the TopN field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RerankRequest) GetTopN() int32 {
	if o == nil || IsNil(o.TopN.Get()) {
		var ret int32
		return ret
	}
	return *o.TopN.Get()
}

// GetTopNOk returns a tuple with the TopN field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RerankRequest) GetTopNOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopN.Get(), o.TopN.IsSet()
}

// HasTopN returns a boolean if a field has been set.
func (o *RerankRequest) HasTopN() bool {
	if o != nil && o.TopN.IsSet() {
		return true
	}

	return false
}

// SetTopN gets a reference to the given NullableInt32 and assigns it to the TopN field.
func (o *RerankRequest) SetTopN(v int32) {
	o.TopN.Set(&v)
}

// SetTopNNil sets the value for TopN to be an explicit nil
func (o *RerankRequest) SetTopNNil() {
	o.TopN.Set(nil)
}

// UnsetTopN ensures that no value is present for TopN, not even an explicit nil
func (o *RerankRequest) UnsetTopN() {
	o.TopN.Unset()
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RerankRequest) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RerankRequest) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *RerankRequest) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *RerankRequest) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *RerankRequest) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *RerankRequest) UnsetUser() {
	o.User.Unset()
}

func (o RerankRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RerankRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["documents"] = o.Documents
	if o.MaxTokensPerDoc.IsSet() {
		toSerialize["max_tokens_per_doc"] = o.MaxTokensPerDoc.Get()
	}
	toSerialize["model"] = o.Model
	toSerialize["query"] = o.Query
	if o.TopN.IsSet() {
		toSerialize["top_n"] = o.TopN.Get()
	}
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	return toSerialize, nil
}

func (o *RerankRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"documents",
		"model",
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRerankRequest := _RerankRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRerankRequest)

	if err != nil {
		return err
	}

	*o = RerankRequest(varRerankRequest)

	return err
}

type NullableRerankRequest struct {
	value *RerankRequest
	isSet bool
}

func (v NullableRerankRequest) Get() *RerankRequest {
	return v.value
}

func (v *NullableRerankRequest) Set(val *RerankRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRerankRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRerankRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRerankRequest(val *RerankRequest) *NullableRerankRequest {
	return &NullableRerankRequest{value: val, isSet: true}
}

func (v NullableRerankRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRerankRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
