/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SearchProviderSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchProviderSchema{}

// SearchProviderSchema One provider a search or fetch instance may name, for the add-tool form.  One schema for both capabilities: the fields they share, then each one's own, which are null on the other's entries.
type SearchProviderSchema struct {
	// The endpoint a tool on this provider uses when it declares no api_base. Null means nothing supplies one, so an api_base is required. One that comes from the deployment's own settings, such as the web_search_url a searxng tool inherits, is shown only to a caller who operates the deployment: nothing else inherits it, an organization's key included.
	DefaultApiBase NullableString `json:"default_api_base,omitempty"`
	// The provider's API documentation.
	DocUrl NullableString `json:"doc_url,omitempty"`
	// Fetch: the formats the page text comes back in.
	Formats []string `json:"formats,omitempty"`
	// Value to send as 'provider'.
	Id string `json:"id"`
	// The names of this deployment's configured and stored tools on this provider, shown only to a caller who operates the deployment.
	Instances []string `json:"instances,omitempty"`
	// Search: true when the API key travels in the request URL.
	KeyInUrl NullableBool `json:"key_in_url,omitempty"`
	// Whether this is a search provider or a fetch provider.
	Kind string `json:"kind"`
	// Search: the most results one call can ask for.
	MaxResults NullableInt32 `json:"max_results,omitempty"`
	// Fetch: the most pages one call can fetch.
	MaxUrlsPerCall NullableInt32 `json:"max_urls_per_call,omitempty"`
	// The native options a tool may set, under the provider's own names. Null when there is no schema for the provider yet, so a tool's options are passed unchecked.
	Options []SearchProviderOptionSchema `json:"options,omitempty"`
	// Search: true when the query travels in the request URL.
	QueryInUrl NullableBool `json:"query_in_url,omitempty"`
	// Fetch: true when the provider runs a page's JavaScript before reading it.
	RendersJavascript NullableBool `json:"renders_javascript,omitempty"`
	// True when this provider has no endpoint of its own, so the tool must say where the backend is.
	RequiresApiBase bool `json:"requires_api_base"`
	// True when a tool on this provider must carry an API key.
	RequiresApiKey bool `json:"requires_api_key"`
	// The library's tier for the provider.
	Tier NullableString `json:"tier,omitempty"`
}

type _SearchProviderSchema SearchProviderSchema

// NewSearchProviderSchema instantiates a new SearchProviderSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchProviderSchema(id string, kind string, requiresApiBase bool, requiresApiKey bool) *SearchProviderSchema {
	this := SearchProviderSchema{}
	this.Id = id
	this.Kind = kind
	this.RequiresApiBase = requiresApiBase
	this.RequiresApiKey = requiresApiKey
	return &this
}

// NewSearchProviderSchemaWithDefaults instantiates a new SearchProviderSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchProviderSchemaWithDefaults() *SearchProviderSchema {
	this := SearchProviderSchema{}
	return &this
}

// GetDefaultApiBase returns the DefaultApiBase field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetDefaultApiBase() string {
	if o == nil || IsNil(o.DefaultApiBase.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultApiBase.Get()
}

// GetDefaultApiBaseOk returns a tuple with the DefaultApiBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetDefaultApiBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultApiBase.Get(), o.DefaultApiBase.IsSet()
}

// HasDefaultApiBase returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasDefaultApiBase() bool {
	if o != nil && o.DefaultApiBase.IsSet() {
		return true
	}

	return false
}

// SetDefaultApiBase gets a reference to the given NullableString and assigns it to the DefaultApiBase field.
func (o *SearchProviderSchema) SetDefaultApiBase(v string) {
	o.DefaultApiBase.Set(&v)
}

// SetDefaultApiBaseNil sets the value for DefaultApiBase to be an explicit nil
func (o *SearchProviderSchema) SetDefaultApiBaseNil() {
	o.DefaultApiBase.Set(nil)
}

// UnsetDefaultApiBase ensures that no value is present for DefaultApiBase, not even an explicit nil
func (o *SearchProviderSchema) UnsetDefaultApiBase() {
	o.DefaultApiBase.Unset()
}

// GetDocUrl returns the DocUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetDocUrl() string {
	if o == nil || IsNil(o.DocUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DocUrl.Get()
}

// GetDocUrlOk returns a tuple with the DocUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetDocUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocUrl.Get(), o.DocUrl.IsSet()
}

// HasDocUrl returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasDocUrl() bool {
	if o != nil && o.DocUrl.IsSet() {
		return true
	}

	return false
}

// SetDocUrl gets a reference to the given NullableString and assigns it to the DocUrl field.
func (o *SearchProviderSchema) SetDocUrl(v string) {
	o.DocUrl.Set(&v)
}

// SetDocUrlNil sets the value for DocUrl to be an explicit nil
func (o *SearchProviderSchema) SetDocUrlNil() {
	o.DocUrl.Set(nil)
}

// UnsetDocUrl ensures that no value is present for DocUrl, not even an explicit nil
func (o *SearchProviderSchema) UnsetDocUrl() {
	o.DocUrl.Unset()
}

// GetFormats returns the Formats field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetFormats() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Formats
}

// GetFormatsOk returns a tuple with the Formats field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetFormatsOk() ([]string, bool) {
	if o == nil || IsNil(o.Formats) {
		return nil, false
	}
	return o.Formats, true
}

// HasFormats returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasFormats() bool {
	if o != nil && !IsNil(o.Formats) {
		return true
	}

	return false
}

// SetFormats gets a reference to the given []string and assigns it to the Formats field.
func (o *SearchProviderSchema) SetFormats(v []string) {
	o.Formats = v
}

// GetId returns the Id field value
func (o *SearchProviderSchema) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SearchProviderSchema) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SearchProviderSchema) SetId(v string) {
	o.Id = v
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *SearchProviderSchema) GetInstances() []string {
	if o == nil || IsNil(o.Instances) {
		var ret []string
		return ret
	}
	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchProviderSchema) GetInstancesOk() ([]string, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []string and assigns it to the Instances field.
func (o *SearchProviderSchema) SetInstances(v []string) {
	o.Instances = v
}

// GetKeyInUrl returns the KeyInUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetKeyInUrl() bool {
	if o == nil || IsNil(o.KeyInUrl.Get()) {
		var ret bool
		return ret
	}
	return *o.KeyInUrl.Get()
}

// GetKeyInUrlOk returns a tuple with the KeyInUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetKeyInUrlOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyInUrl.Get(), o.KeyInUrl.IsSet()
}

// HasKeyInUrl returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasKeyInUrl() bool {
	if o != nil && o.KeyInUrl.IsSet() {
		return true
	}

	return false
}

// SetKeyInUrl gets a reference to the given NullableBool and assigns it to the KeyInUrl field.
func (o *SearchProviderSchema) SetKeyInUrl(v bool) {
	o.KeyInUrl.Set(&v)
}

// SetKeyInUrlNil sets the value for KeyInUrl to be an explicit nil
func (o *SearchProviderSchema) SetKeyInUrlNil() {
	o.KeyInUrl.Set(nil)
}

// UnsetKeyInUrl ensures that no value is present for KeyInUrl, not even an explicit nil
func (o *SearchProviderSchema) UnsetKeyInUrl() {
	o.KeyInUrl.Unset()
}

// GetKind returns the Kind field value
func (o *SearchProviderSchema) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *SearchProviderSchema) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *SearchProviderSchema) SetKind(v string) {
	o.Kind = v
}

// GetMaxResults returns the MaxResults field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetMaxResults() int32 {
	if o == nil || IsNil(o.MaxResults.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxResults.Get()
}

// GetMaxResultsOk returns a tuple with the MaxResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetMaxResultsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxResults.Get(), o.MaxResults.IsSet()
}

// HasMaxResults returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasMaxResults() bool {
	if o != nil && o.MaxResults.IsSet() {
		return true
	}

	return false
}

// SetMaxResults gets a reference to the given NullableInt32 and assigns it to the MaxResults field.
func (o *SearchProviderSchema) SetMaxResults(v int32) {
	o.MaxResults.Set(&v)
}

// SetMaxResultsNil sets the value for MaxResults to be an explicit nil
func (o *SearchProviderSchema) SetMaxResultsNil() {
	o.MaxResults.Set(nil)
}

// UnsetMaxResults ensures that no value is present for MaxResults, not even an explicit nil
func (o *SearchProviderSchema) UnsetMaxResults() {
	o.MaxResults.Unset()
}

// GetMaxUrlsPerCall returns the MaxUrlsPerCall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetMaxUrlsPerCall() int32 {
	if o == nil || IsNil(o.MaxUrlsPerCall.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxUrlsPerCall.Get()
}

// GetMaxUrlsPerCallOk returns a tuple with the MaxUrlsPerCall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetMaxUrlsPerCallOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxUrlsPerCall.Get(), o.MaxUrlsPerCall.IsSet()
}

// HasMaxUrlsPerCall returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasMaxUrlsPerCall() bool {
	if o != nil && o.MaxUrlsPerCall.IsSet() {
		return true
	}

	return false
}

// SetMaxUrlsPerCall gets a reference to the given NullableInt32 and assigns it to the MaxUrlsPerCall field.
func (o *SearchProviderSchema) SetMaxUrlsPerCall(v int32) {
	o.MaxUrlsPerCall.Set(&v)
}

// SetMaxUrlsPerCallNil sets the value for MaxUrlsPerCall to be an explicit nil
func (o *SearchProviderSchema) SetMaxUrlsPerCallNil() {
	o.MaxUrlsPerCall.Set(nil)
}

// UnsetMaxUrlsPerCall ensures that no value is present for MaxUrlsPerCall, not even an explicit nil
func (o *SearchProviderSchema) UnsetMaxUrlsPerCall() {
	o.MaxUrlsPerCall.Unset()
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetOptions() []SearchProviderOptionSchema {
	if o == nil {
		var ret []SearchProviderOptionSchema
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetOptionsOk() ([]SearchProviderOptionSchema, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []SearchProviderOptionSchema and assigns it to the Options field.
func (o *SearchProviderSchema) SetOptions(v []SearchProviderOptionSchema) {
	o.Options = v
}

// GetQueryInUrl returns the QueryInUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetQueryInUrl() bool {
	if o == nil || IsNil(o.QueryInUrl.Get()) {
		var ret bool
		return ret
	}
	return *o.QueryInUrl.Get()
}

// GetQueryInUrlOk returns a tuple with the QueryInUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetQueryInUrlOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryInUrl.Get(), o.QueryInUrl.IsSet()
}

// HasQueryInUrl returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasQueryInUrl() bool {
	if o != nil && o.QueryInUrl.IsSet() {
		return true
	}

	return false
}

// SetQueryInUrl gets a reference to the given NullableBool and assigns it to the QueryInUrl field.
func (o *SearchProviderSchema) SetQueryInUrl(v bool) {
	o.QueryInUrl.Set(&v)
}

// SetQueryInUrlNil sets the value for QueryInUrl to be an explicit nil
func (o *SearchProviderSchema) SetQueryInUrlNil() {
	o.QueryInUrl.Set(nil)
}

// UnsetQueryInUrl ensures that no value is present for QueryInUrl, not even an explicit nil
func (o *SearchProviderSchema) UnsetQueryInUrl() {
	o.QueryInUrl.Unset()
}

// GetRendersJavascript returns the RendersJavascript field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetRendersJavascript() bool {
	if o == nil || IsNil(o.RendersJavascript.Get()) {
		var ret bool
		return ret
	}
	return *o.RendersJavascript.Get()
}

// GetRendersJavascriptOk returns a tuple with the RendersJavascript field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetRendersJavascriptOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RendersJavascript.Get(), o.RendersJavascript.IsSet()
}

// HasRendersJavascript returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasRendersJavascript() bool {
	if o != nil && o.RendersJavascript.IsSet() {
		return true
	}

	return false
}

// SetRendersJavascript gets a reference to the given NullableBool and assigns it to the RendersJavascript field.
func (o *SearchProviderSchema) SetRendersJavascript(v bool) {
	o.RendersJavascript.Set(&v)
}

// SetRendersJavascriptNil sets the value for RendersJavascript to be an explicit nil
func (o *SearchProviderSchema) SetRendersJavascriptNil() {
	o.RendersJavascript.Set(nil)
}

// UnsetRendersJavascript ensures that no value is present for RendersJavascript, not even an explicit nil
func (o *SearchProviderSchema) UnsetRendersJavascript() {
	o.RendersJavascript.Unset()
}

// GetRequiresApiBase returns the RequiresApiBase field value
func (o *SearchProviderSchema) GetRequiresApiBase() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresApiBase
}

// GetRequiresApiBaseOk returns a tuple with the RequiresApiBase field value
// and a boolean to check if the value has been set.
func (o *SearchProviderSchema) GetRequiresApiBaseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresApiBase, true
}

// SetRequiresApiBase sets field value
func (o *SearchProviderSchema) SetRequiresApiBase(v bool) {
	o.RequiresApiBase = v
}

// GetRequiresApiKey returns the RequiresApiKey field value
func (o *SearchProviderSchema) GetRequiresApiKey() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresApiKey
}

// GetRequiresApiKeyOk returns a tuple with the RequiresApiKey field value
// and a boolean to check if the value has been set.
func (o *SearchProviderSchema) GetRequiresApiKeyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresApiKey, true
}

// SetRequiresApiKey sets field value
func (o *SearchProviderSchema) SetRequiresApiKey(v bool) {
	o.RequiresApiKey = v
}

// GetTier returns the Tier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchProviderSchema) GetTier() string {
	if o == nil || IsNil(o.Tier.Get()) {
		var ret string
		return ret
	}
	return *o.Tier.Get()
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchProviderSchema) GetTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tier.Get(), o.Tier.IsSet()
}

// HasTier returns a boolean if a field has been set.
func (o *SearchProviderSchema) HasTier() bool {
	if o != nil && o.Tier.IsSet() {
		return true
	}

	return false
}

// SetTier gets a reference to the given NullableString and assigns it to the Tier field.
func (o *SearchProviderSchema) SetTier(v string) {
	o.Tier.Set(&v)
}

// SetTierNil sets the value for Tier to be an explicit nil
func (o *SearchProviderSchema) SetTierNil() {
	o.Tier.Set(nil)
}

// UnsetTier ensures that no value is present for Tier, not even an explicit nil
func (o *SearchProviderSchema) UnsetTier() {
	o.Tier.Unset()
}

func (o SearchProviderSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchProviderSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultApiBase.IsSet() {
		toSerialize["default_api_base"] = o.DefaultApiBase.Get()
	}
	if o.DocUrl.IsSet() {
		toSerialize["doc_url"] = o.DocUrl.Get()
	}
	if o.Formats != nil {
		toSerialize["formats"] = o.Formats
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	if o.KeyInUrl.IsSet() {
		toSerialize["key_in_url"] = o.KeyInUrl.Get()
	}
	toSerialize["kind"] = o.Kind
	if o.MaxResults.IsSet() {
		toSerialize["max_results"] = o.MaxResults.Get()
	}
	if o.MaxUrlsPerCall.IsSet() {
		toSerialize["max_urls_per_call"] = o.MaxUrlsPerCall.Get()
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	if o.QueryInUrl.IsSet() {
		toSerialize["query_in_url"] = o.QueryInUrl.Get()
	}
	if o.RendersJavascript.IsSet() {
		toSerialize["renders_javascript"] = o.RendersJavascript.Get()
	}
	toSerialize["requires_api_base"] = o.RequiresApiBase
	toSerialize["requires_api_key"] = o.RequiresApiKey
	if o.Tier.IsSet() {
		toSerialize["tier"] = o.Tier.Get()
	}
	return toSerialize, nil
}

func (o *SearchProviderSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"kind",
		"requires_api_base",
		"requires_api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchProviderSchema := _SearchProviderSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchProviderSchema)

	if err != nil {
		return err
	}

	*o = SearchProviderSchema(varSearchProviderSchema)

	return err
}

type NullableSearchProviderSchema struct {
	value *SearchProviderSchema
	isSet bool
}

func (v NullableSearchProviderSchema) Get() *SearchProviderSchema {
	return v.value
}

func (v *NullableSearchProviderSchema) Set(val *SearchProviderSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchProviderSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchProviderSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchProviderSchema(val *SearchProviderSchema) *NullableSearchProviderSchema {
	return &NullableSearchProviderSchema{value: val, isSet: true}
}

func (v NullableSearchProviderSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchProviderSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
