/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// Content8 struct for Content8
type Content8 struct {
	MRWebSearchToolResultError    *MRWebSearchToolResultError
	ArrayOfMRWebSearchResultBlock *[]MRWebSearchResultBlock
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Content8) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MRWebSearchToolResultError
	err = json.Unmarshal(data, &dst.MRWebSearchToolResultError)
	if err == nil {
		jsonMRWebSearchToolResultError, _ := json.Marshal(dst.MRWebSearchToolResultError)
		if string(jsonMRWebSearchToolResultError) == "{}" { // empty struct
			dst.MRWebSearchToolResultError = nil
		} else {
			return nil // data stored in dst.MRWebSearchToolResultError, return on the first match
		}
	} else {
		dst.MRWebSearchToolResultError = nil
	}

	// try to unmarshal JSON data into ArrayOfMRWebSearchResultBlock
	err = json.Unmarshal(data, &dst.ArrayOfMRWebSearchResultBlock)
	if err == nil {
		jsonArrayOfMRWebSearchResultBlock, _ := json.Marshal(dst.ArrayOfMRWebSearchResultBlock)
		if string(jsonArrayOfMRWebSearchResultBlock) == "{}" { // empty struct
			dst.ArrayOfMRWebSearchResultBlock = nil
		} else {
			return nil // data stored in dst.ArrayOfMRWebSearchResultBlock, return on the first match
		}
	} else {
		dst.ArrayOfMRWebSearchResultBlock = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Content8)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Content8) MarshalJSON() ([]byte, error) {
	if src.MRWebSearchToolResultError != nil {
		return json.Marshal(&src.MRWebSearchToolResultError)
	}

	if src.ArrayOfMRWebSearchResultBlock != nil {
		return json.Marshal(&src.ArrayOfMRWebSearchResultBlock)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableContent8 struct {
	value *Content8
	isSet bool
}

func (v NullableContent8) Get() *Content8 {
	return v.value
}

func (v *NullableContent8) Set(val *Content8) {
	v.value = val
	v.isSet = true
}

func (v NullableContent8) IsSet() bool {
	return v.isSet
}

func (v *NullableContent8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent8(val *Content8) *NullableContent8 {
	return &NullableContent8{value: val, isSet: true}
}

func (v NullableContent8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
