/*
otari

Otari, an OpenAI-compatible LLM gateway with API key management

API version: 0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ActiveOrganizationMemberCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActiveOrganizationMemberCreateRequest{}

// ActiveOrganizationMemberCreateRequest Add someone to the caller's organization, optionally into workspaces at once.
type ActiveOrganizationMemberCreateRequest struct {
	Email                string                       `json:"email"`
	Role                 *string                      `json:"role,omitempty"`
	WorkspaceAssignments []WorkspaceAssignmentRequest `json:"workspace_assignments,omitempty"`
}

type _ActiveOrganizationMemberCreateRequest ActiveOrganizationMemberCreateRequest

// NewActiveOrganizationMemberCreateRequest instantiates a new ActiveOrganizationMemberCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveOrganizationMemberCreateRequest(email string) *ActiveOrganizationMemberCreateRequest {
	this := ActiveOrganizationMemberCreateRequest{}
	this.Email = email
	var role string = "member"
	this.Role = &role
	return &this
}

// NewActiveOrganizationMemberCreateRequestWithDefaults instantiates a new ActiveOrganizationMemberCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveOrganizationMemberCreateRequestWithDefaults() *ActiveOrganizationMemberCreateRequest {
	this := ActiveOrganizationMemberCreateRequest{}
	var role string = "member"
	this.Role = &role
	return &this
}

// GetEmail returns the Email field value
func (o *ActiveOrganizationMemberCreateRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ActiveOrganizationMemberCreateRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ActiveOrganizationMemberCreateRequest) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ActiveOrganizationMemberCreateRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveOrganizationMemberCreateRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ActiveOrganizationMemberCreateRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ActiveOrganizationMemberCreateRequest) SetRole(v string) {
	o.Role = &v
}

// GetWorkspaceAssignments returns the WorkspaceAssignments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActiveOrganizationMemberCreateRequest) GetWorkspaceAssignments() []WorkspaceAssignmentRequest {
	if o == nil {
		var ret []WorkspaceAssignmentRequest
		return ret
	}
	return o.WorkspaceAssignments
}

// GetWorkspaceAssignmentsOk returns a tuple with the WorkspaceAssignments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActiveOrganizationMemberCreateRequest) GetWorkspaceAssignmentsOk() ([]WorkspaceAssignmentRequest, bool) {
	if o == nil || IsNil(o.WorkspaceAssignments) {
		return nil, false
	}
	return o.WorkspaceAssignments, true
}

// HasWorkspaceAssignments returns a boolean if a field has been set.
func (o *ActiveOrganizationMemberCreateRequest) HasWorkspaceAssignments() bool {
	if o != nil && !IsNil(o.WorkspaceAssignments) {
		return true
	}

	return false
}

// SetWorkspaceAssignments gets a reference to the given []WorkspaceAssignmentRequest and assigns it to the WorkspaceAssignments field.
func (o *ActiveOrganizationMemberCreateRequest) SetWorkspaceAssignments(v []WorkspaceAssignmentRequest) {
	o.WorkspaceAssignments = v
}

func (o ActiveOrganizationMemberCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActiveOrganizationMemberCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if o.WorkspaceAssignments != nil {
		toSerialize["workspace_assignments"] = o.WorkspaceAssignments
	}
	return toSerialize, nil
}

func (o *ActiveOrganizationMemberCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActiveOrganizationMemberCreateRequest := _ActiveOrganizationMemberCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActiveOrganizationMemberCreateRequest)

	if err != nil {
		return err
	}

	*o = ActiveOrganizationMemberCreateRequest(varActiveOrganizationMemberCreateRequest)

	return err
}

type NullableActiveOrganizationMemberCreateRequest struct {
	value *ActiveOrganizationMemberCreateRequest
	isSet bool
}

func (v NullableActiveOrganizationMemberCreateRequest) Get() *ActiveOrganizationMemberCreateRequest {
	return v.value
}

func (v *NullableActiveOrganizationMemberCreateRequest) Set(val *ActiveOrganizationMemberCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveOrganizationMemberCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveOrganizationMemberCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveOrganizationMemberCreateRequest(val *ActiveOrganizationMemberCreateRequest) *NullableActiveOrganizationMemberCreateRequest {
	return &NullableActiveOrganizationMemberCreateRequest{value: val, isSet: true}
}

func (v NullableActiveOrganizationMemberCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveOrganizationMemberCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
